// routes to implement

const startScreen = '/start/';
const mapScreen = '/map/';
const guideScreen = '/guide/';
const plantsScreen = '/plants/';
const plantDetailsScreen = '/plantdetails/';
const plantsListView = '/plantslistview/';
const debugScreen = '/debugscreen/';
const impressumScreen = '/impressum/';

final distriDict = {
  'Acer campestre': 'Europe, N. Africa, W. Asia',
  'Acer monspessulanum': 'S. Europe, N. Africa, W. Asia',
  'Acer platanoides': 'Europe, W. Asia',
  'Acer pseudoplatanus': 'Europe, W. Asia',
  'Alnus glutinosa': 'Europe, N. Africa, W. & C. Asia',
  'Amelanchier ovalis': 'Europe, N. Africa, W. & C. Asia',
  'Anemone nemorosa': 'Europe, N. Africa, W. & C. Asia',
  'Athyrium filix-femina': 'Temperate regions of N. Hemisphere',
  'Berberis vulgaris': 'Europe, N. Africa, W. & C. Asia',
  'Betula pendula': 'Europe, N. Africa, W. & C. Asia',
  'Betula pubescens': 'Europe, N. Africa, W. & C. Asia',
  'Brachypodium sylvaticum': 'Europe, N. Africa, W. & C. Asia',
  'Carex brizoides': 'Europe, W. Asia',
  'Carpinus betulus': 'Europe, W. & C. Asia',
  'Cornus sanguinea': 'Europe, N. Africa, W. & C. Asia',
  'Corylus avellana': 'Europe, N. Africa, W. & C. Asia',
  'Crataegus laevigata agg': 'Europe, N. Africa, W. Asia',
  'Crataegus monogyna': 'Europe, N. Africa, W. & C. Asia',
  'Cytisus scoparius': 'Europe, N. Africa, W. Asia',
  'Euonymus europaeus': 'Europe, N. Africa, W. & C. Asia',
  'Fagus sylvatica': 'Europe, W. Asia',
  'Frangula alnus': 'Europe, N. Africa, W. & C. Asia',
  'Fraxinus excelsior': 'Europe, N. Africa, W. & C. Asia',
  'Galium odoratum': 'Europe, N. Africa, W. & C. Asia',
  'Galium sylvaticum': 'Europe, W. Asia',
  'Ilex aquifolium': 'Europe, N. Africa, W. & C. Asia',
  'Impatiens noli-tangere': 'Europe, W. & C. Asia',
  'Lamium galeobdolon': 'Europe, N. Africa, W. & C. Asia',
  'Larix decidua var. polonica': 'C. Europe',
  'Lonicera periclymenum': 'Europe, N. Africa, W. & C. Asia',
  'Malus sylvestris': 'Europe, W. & C. Asia',
  'Oxalis acetosella': 'Europe, N. Africa, W. & C. Asia',
  'Pinus sylvestris': 'Europe, N. Africa, W. & C. Asia',
  'Poa nemoralis': 'Europe, N. Africa, W. & C. Asia',
  'Populus tremula': 'Europe, N. Africa, W. & C. Asia',
  'Potentilla sterilis': 'Europe, N. Africa, W. Asia',
  'Prunus avium': 'Europe, N. Africa, W. & C. Asia',
  'Prunus cerasifera': 'S.E. Europe, W. Asia',
  'Prunus padus': 'Europe, N. Africa, W. & C. Asia',
  'Prunus spinosa': 'Europe, N. Africa, W. & C. Asia',
  'Pyrus pyraster': 'Europe, W. & C. Asia',
  'Pyrus pyraster agg': 'Europe, W. & C. Asia',
  'Quercus patrea': 'S. Europe, W. Asia',
  'Quercus petraea': 'Europe, W. Asia',
  'Quercus robur': 'Europe, N. Africa, W. & C. Asia',
  'Rhammus cathartica': 'Europe, N. Africa, W. & C. Asia',
  'Rhamnus frangula': 'Europe, N. Africa, W. & C. Asia',
  'Ribes rubrum': 'Europe, N. Africa, W. & C. Asia',
  'Ribes rubrum s. str.': 'Europe, N. Africa, W. & C. Asia',
  'Rosa arvensis': 'Europe, N. Africa, W. & C. Asia',
  'Rosa canina agg': 'Europe, N. Africa, W. & C. Asia',
  'Rubus caesius': 'Europe, N. Africa, W. & C. Asia',
  'Rubus idaeus': 'Europe, N. Africa, W. & C. Asia',
  'Rubus sect. Rubus': 'Europe, N. Africa, W. & C. Asia',
  'Salix alba': 'Europe, N. Africa, W. & C. Asia',
  'Salix aurita': 'Europe, N. Africa, W. & C. Asia',
  'Salix caprea': 'Europe, N. Africa, W. & C. Asia',
  'Salix purpurea': 'Europe, N. Africa, W. & C. Asia',
  'Sambucus n.': 'Europe, N. Africa, W. & C. Asia',
  'Sambucus racemosa': 'Europe, N. Africa, W. & C. Asia',
  'Sorbus aucuparia': 'Europe, N. Africa, W. & C. Asia',
  'Sorbus torminalis': 'Europe, N. Africa, W. & C. Asia',
  'Stellaria holostea': 'Europe, N. Africa, W. & C. Asia',
  'Taxus baccata': 'Europe, N. Africa, W. & C. Asia',
  'Tilia cordata': 'Europe, W. & C. Asia',
  'Tilia platyphyllos': 'Europe, W. & C. Asia',
  'Tilia tomentosa': 'S.E. Europe, W. Asia',
  'Ulmus glabra': 'Europe, W. & C. Asia',
  'Ulmus laevis': 'Europe, W. & C. Asia',
  'Ulmus minor': 'Europe, N. Africa, W. & C. Asia',
  'Vaccinium corymbosum': 'E. North America',
  'Viburnum opulus': 'Europe, N. Africa, W. & C. Asia',
  'Viola reichenbachiana': 'Europe, N. Africa, W. & C. Asia'
};
