Map<String, Map<String, dynamic>> forestsDB = {
  'Zichow': {
    'Projektname': 'Zichow',
    'Standort': 'Zichow',
    'MapsURL': ' https://maps.app.goo.gl/qdTvpswtfUMyxvm48 ',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2020,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 700,
    'Baumanzahl': 2200,
    'Anz. freiw.\nHelfer:innen': 25,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': 'Bagger teilweise'
  },
  'Darmstadt': {
    'Projektname': 'Darmstadt',
    'Standort': 'Darmstadt ',
    'MapsURL': 'https://goo.gl/maps/As9Z6TDkpbSS9M3e7',
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2021,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 250,
    'Baumanzahl': 630,
    'Anz. freiw.\nHelfer:innen': 60,
    'Anz. \nKinder': 40,
    'Alter/Klassenstufe der Kinder': '3. bis 7. Klasse',
    'Bodenbearbeitung': 'Bagger'
  },
  'Kinderhort Oderpiraten': {
    'Projektname': 'Kinderhort Oderpiraten',
    'Standort': 'Frankfurt Oder ',
    'MapsURL': 'https://maps.app.goo.gl/aWchr4qH53hB2bZA6',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2021,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 150,
    'Baumanzahl': 360,
    'Anz. freiw.\nHelfer:innen': 100,
    'Anz. \nKinder': 30,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'Bagger'
  },
  'Kindergarten am Wurzelberg + Kita Kinderland (auf dem selben Gelände)': {
    'Projektname':
        'Kindergarten am Wurzelberg + Kita Kinderland (auf dem selben Gelände)',
    'Standort': 'Ludwigsfelde ',
    'MapsURL': 'https://maps.app.goo.gl/c29N783JrMNxU3cD6',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2021,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 150,
    'Baumanzahl': 600,
    'Anz. freiw.\nHelfer:innen': 100,
    'Anz. \nKinder': 30,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'Bagger'
  },
  'Rozwarowo': {
    'Projektname': 'Rozwarowo',
    'Standort': 'Rozwarowo ',
    'MapsURL': 'https://maps.app.goo.gl/yA9J9UF5SDZ8DKYn8',
    'Bundesland': null,
    'Land': 'Polen',
    'Pflanzjahr': 2021,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 1.5,
    'Baumanzahl': 4500,
    'Anz. freiw.\nHelfer:innen': 150,
    'Anz. \nKinder': 25,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': null
  },
  'Grießheim Westring': {
    'Projektname': 'Grießheim Westring',
    'Standort': 'Grießheim ',
    'MapsURL': 'https://goo.gl/maps/jj61Add5W4dBMPjSA ',
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2021,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 500,
    'Baumanzahl': 1500,
    'Anz. freiw.\nHelfer:innen': 150,
    'Anz. \nKinder': 60,
    'Alter/Klassenstufe der Kinder': '3. bis 4. Klasse',
    'Bodenbearbeitung': 'Bagger'
  },
  'Herford': {
    'Projektname': 'Herford',
    'Standort': 'Herford ',
    'MapsURL': 'https://maps.app.goo.gl/CCbFyr6Mz7DVEhJG8 ',
    'Bundesland': 'NRW',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Frühling',
    'Fläche in qm': 250,
    'Baumanzahl': 750,
    'Anz. freiw.\nHelfer:innen': 100,
    'Anz. \nKinder': 20,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'Bagger'
  },
  'Griesheim Friedhof und Westring': {
    'Projektname': 'Griesheim Friedhof und Westring',
    'Standort': 'Grießheim ',
    'MapsURL':
        'https://goo.gl/maps/D4DCSpBoz2Nrm1qg6 \n\t\t\thttps://goo.gl/maps/4jDQEZzoVfmPy1ao8 ',
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 750,
    'Baumanzahl': 2250,
    'Anz. freiw.\nHelfer:innen': 70,
    'Anz. \nKinder': 80,
    'Alter/Klassenstufe der Kinder': '3. bis 4. Klasse',
    'Bodenbearbeitung': 'Bagger'
  },
  'Agrofert': {
    'Projektname': 'Agrofert',
    'Standort': 'Lutherstadt Wittemberg ',
    'MapsURL': 'https://maps.app.goo.gl/ZRCuDU3LJFb2nQYa9 ',
    'Bundesland': 'Sachsen-Anhalt',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 70,
    'Baumanzahl': 181,
    'Anz. freiw.\nHelfer:innen': 7,
    'Anz. \nKinder': 30,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'keine Baggerarbeiten'
  },
  'Silberahorn': {
    'Projektname': 'Silberahorn',
    'Standort': 'Potsdam ',
    'MapsURL': 'https://maps.app.goo.gl/enps3GCpxrfurtnB8 ',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 100,
    'Baumanzahl': 274,
    'Anz. freiw.\nHelfer:innen': 5,
    'Anz. \nKinder': 30,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'keine Baggerarbeiten'
  },
  'Am Jungfernsee': {
    'Projektname': 'Am Jungfernsee',
    'Standort': 'Potsdam ',
    'MapsURL': 'https://maps.app.goo.gl/thAPnQDVU5WExtDN9 ',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 75,
    'Baumanzahl': 241,
    'Anz. freiw.\nHelfer:innen': 9,
    'Anz. \nKinder': 30,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'Bagger'
  },
  'Oderknirpse': {
    'Projektname': 'Oderknirpse',
    'Standort': 'Frankfurt Oder ',
    'MapsURL': 'https://maps.app.goo.gl/UheHsH2nSdmgxY8QA ',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 140,
    'Baumanzahl': 381,
    'Anz. freiw.\nHelfer:innen': 8,
    'Anz. \nKinder': 40,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'keine Baggerarbeiten'
  },
  'Kleine Füße Naseweiß': {
    'Projektname': 'Kleine Füße Naseweiß',
    'Standort': 'Berlin ',
    'MapsURL': 'https://maps.app.goo.gl/hhuV4pTvjsUWu2kL7 ',
    'Bundesland': 'Berlin',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 150,
    'Baumanzahl': 466,
    'Anz. freiw.\nHelfer:innen': 17,
    'Anz. \nKinder': 80,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'keine Baggerarbeiten'
  },
  'Kita im Grünen': {
    'Projektname': 'Kita im Grünen',
    'Standort': 'Berlin ',
    'MapsURL': 'https://maps.app.goo.gl/nKJXKKBYEu34KNSh9 ',
    'Bundesland': 'Berlin',
    'Land': 'Deutschland',
    'Pflanzjahr': 2022,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 95,
    'Baumanzahl': 226,
    'Anz. freiw.\nHelfer:innen': 13,
    'Anz. \nKinder': 30,
    'Alter/Klassenstufe der Kinder': 'Kita',
    'Bodenbearbeitung': 'keine Baggerarbeiten'
  },
  'Grießheim 3.0': {
    'Projektname': 'Grießheim 3.0',
    'Standort': 'Grießheim',
    'MapsURL': 'https://maps.app.goo.gl/QSAxKVjFtzK5o8YJ7 ',
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 1.5,
    'Baumanzahl': 6000,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': 'Bodenvorbereitung durch externes Unternehmen'
  },
  'TGE Eberswalde': {
    'Projektname': 'TGE Eberswalde',
    'Standort': 'Eberswalde ',
    'MapsURL': 'https://maps.app.goo.gl/3973ewcVo6sUsTcj7 ',
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2023,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 600,
    'Baumanzahl': 900,
    'Anz. freiw.\nHelfer:innen': 30,
    'Anz. \nKinder': 15,
    'Alter/Klassenstufe der Kinder': '3. Klasse',
    'Bodenbearbeitung': 'Bodenbearbeitung durch uns'
  },
  'Schwäbisch Hall Biodiversitäts-Hain Phase 1': {
    'Projektname': 'Schwäbisch Hall Biodiversitäts-Hain Phase 1',
    'Standort': 'Schwäbsich Hall ',
    'MapsURL': 'https://maps.app.goo.gl/cPZtW7kyqDnRwf9dA ',
    'Bundesland': 'Baden Württemberg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2023,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 600,
    'Baumanzahl': 1800,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 150,
    'Alter/Klassenstufe der Kinder': 'noch ergänzen',
    'Bodenbearbeitung': null
  },
  'Hanau': {
    'Projektname': 'Hanau',
    'Standort': 'Hanau (FFM) ',
    'MapsURL': 'https://maps.app.goo.gl/9VVVq4Bu71doTQ8r5 ',
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2023,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 150,
    'Baumanzahl': 450,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 60,
    'Alter/Klassenstufe der Kinder': '7. Klasse',
    'Bodenbearbeitung': null
  },
  'Rüsselsheim': {
    'Projektname': 'Rüsselsheim',
    'Standort': 'Rüsselsheim, Paul -Ehrlich-Str. 15-19, 65428 Rüsselsheim ',
    'MapsURL': 'https://maps.app.goo.gl/UC7chTT37YG8rSUi8 ',
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2023,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 250,
    'Baumanzahl': 700,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': '3-6 Jahre',
    'Bodenbearbeitung': null
  },
  'Pankow Seniorenresidenz Food Forest + Tiny Forest': {
    'Projektname': 'Pankow Seniorenresidenz Food Forest + Tiny Forest',
    'Standort': 'Berlin ',
    'MapsURL': 'https://maps.app.goo.gl/x1f2z3n8Ksbk8R3h8 ',
    'Bundesland': 'Berlin',
    'Land': 'Deutschland',
    'Pflanzjahr': 2023,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 200,
    'Baumanzahl': 285,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': 'noch ergänzen',
    'Bodenbearbeitung': null
  },
  'Mühlheim': {
    'Projektname': 'Mühlheim',
    'Standort': 'Mühlheim am Main ',
    'MapsURL': 'https://maps.app.goo.gl/GaNjDGjy5HK6Hxof9 ',
    'Bundesland': 'Mühlheim',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Frühling',
    'Fläche in qm': 200,
    'Baumanzahl': 600,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': 'noch ergänzen',
    'Bodenbearbeitung': null
  },
  'HSBI (Bielefeld)': {
    'Projektname': 'HSBI (Bielefeld)',
    'Standort': 'Bielefeld ',
    'MapsURL': 'https://maps.app.goo.gl/F3WBqLorFhsapxp58 ',
    'Bundesland': 'Nordrhein-Westphalen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Frühling',
    'Fläche in qm': 200,
    'Baumanzahl': 600,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': 'noch ergänzen',
    'Bodenbearbeitung': null
  },
  'TANO Nordsee': {
    'Projektname': 'TANO Nordsee',
    'Standort': 'Jever und Bad Zwischenahn',
    'MapsURL': null,
    'Bundesland': 'Niedersachsen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Frühling',
    'Fläche in qm': 0,
    'Baumanzahl': null,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': null
  },
  'Rudersberg': {
    'Projektname': 'Rudersberg',
    'Standort': 'Rudersberg',
    'MapsURL': null,
    'Bundesland': 'Baden Württemberg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Frühling',
    'Fläche in qm': 205,
    'Baumanzahl': null,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': null
  },
  'Darmstdt Dieburg': {
    'Projektname': 'Darmstdt Dieburg',
    'Standort': 'Darmstadt-Dieburg, John-F.-Kennedy-Schule Münster',
    'MapsURL': null,
    'Bundesland': 'Hessen',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 320,
    'Baumanzahl': null,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': null
  },
  'Oranienburg': {
    'Projektname': 'Oranienburg',
    'Standort': null,
    'MapsURL': null,
    'Bundesland': 'Brandenburg',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': 1150,
    'Baumanzahl': null,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': null
  },
  'DUH': {
    'Projektname': 'DUH',
    'Standort': 'Hamburg, Leipzig, Berlin',
    'MapsURL': null,
    'Bundesland': 'Hamburg, Sachsen, Berlin',
    'Land': 'Deutschland',
    'Pflanzjahr': 2024,
    'Pflanzzeitpunkt': 'Herbst',
    'Fläche in qm': '3 mal ca. 270qm',
    'Baumanzahl': null,
    'Anz. freiw.\nHelfer:innen': 0,
    'Anz. \nKinder': 0,
    'Alter/Klassenstufe der Kinder': null,
    'Bodenbearbeitung': null
  }
};

// Map<String, <Map<String, int>> forests_db = {


// }