// this is the biggest data file defining the PlantData class and holding a Map of the most common and some rare european trees and bushes,
// it shall also include herbs and every plant species used in the tiny forest project

class PlantData {
  final String scientificName;
  final String commonName;
  final String pathPicture;
  final String plantType;
  final String distribution;
  final String maxSizeMeters;
  final int totalPlanted;
  final String lifeExpectancyYears;
  final String frequency;
  final String habitat;
  final String leafType;
  final String floweringSeason;
  final String conservationStatus;
  final String interestingFact;

  PlantData(
      {required this.scientificName,
      required this.commonName,
      required this.distribution,
      required this.maxSizeMeters,
      required this.totalPlanted,
      required this.lifeExpectancyYears,
      required this.frequency,
      required this.habitat,
      required this.leafType,
      required this.floweringSeason,
      required this.conservationStatus,
      required this.interestingFact,
      required this.pathPicture,
      required this.plantType});
}

Map<String, PlantData> allPlants = {
  "Acer campestre.": PlantData(
    scientificName: "Acer campestre",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Feldahorn",
    distribution: "ToBeDone",
    totalPlanted: 141,
    maxSizeMeters: "Varies, commonly 10-15 meters.",
    lifeExpectancyYears: "Approximately 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "The field maple has distinctive three-lobed leaves.",
  ),
  "Acer monspessulanum.": PlantData(
    scientificName: "Acer monspessulanum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Felsenahorn",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "Up to 10 meters.",
    lifeExpectancyYears: "About 100 years.",
    frequency: "Common in its range.",
    habitat: "Dry woods and rocky places.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Also known as Montpellier maple, it's native to the Mediterranean region.",
  ),
  "Acer platanoides.": PlantData(
    scientificName: "Acer platanoides",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Spitz-Ahorn",
    distribution: "ToBeDone",
    totalPlanted: 90,
    maxSizeMeters: "Typically 20-25 meters.",
    lifeExpectancyYears: "Around 250 years.",
    frequency: "Common.",
    habitat: "Various, often in urban areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Norway maple is valued for its shade and attractive foliage.",
  ),
  "Acer pseudoplatanus.": PlantData(
    scientificName: "Acer pseudoplatanus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Bergahorn",
    distribution: "ToBeDone",
    totalPlanted: 303,
    maxSizeMeters: "Can reach 40 meters.",
    lifeExpectancyYears: "Up to 400 years.",
    frequency: "Common.",
    habitat: "Woodlands and mixed forests.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Sycamore maple is known for its large, palmately lobed leaves.",
  ),
  "Alnus glutinosa.": PlantData(
    scientificName: "Alnus glutinosa",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Schwarzerle",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "Typically 20-25 meters.",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Wetlands and riverbanks.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common alder is associated with wet or waterlogged soils.",
  ),
  "Amelanchier ovalis.": PlantData(
    scientificName: "Amelanchier ovalis",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Gewöhnliche Felsenbirne",
    distribution: "ToBeDone",
    totalPlanted: 63,
    maxSizeMeters: "Usually 3-8 meters.",
    lifeExpectancyYears: "Up to 50 years.",
    frequency: "Common.",
    habitat: "Woodlands and heathlands.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Serviceberries produce edible berries.",
  ),
  "Anemone nemorosa.": PlantData(
    scientificName: "Anemone nemorosa",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Buschwindröschen",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 10-30 cm.",
    lifeExpectancyYears: "About 50 years.",
    frequency: "Common.",
    habitat: "Woodlands and meadows.",
    leafType: "Deciduous.",
    floweringSeason: "March to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Also known as wood anemone, it spreads by rhizomes.",
  ),
  "Athyrium filix-femina.": PlantData(
    scientificName: "Athyrium filix-femina",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Wald-Frauenfarn",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "Can reach 1 meter.",
    lifeExpectancyYears: "Up to 100 years.",
    frequency: "Common.",
    habitat: "Woodlands and shady areas.",
    leafType: "Deciduous.",
    floweringSeason: "Not applicable (fern).",
    conservationStatus: "Least Concern.",
    interestingFact: "Lady fern is a common woodland fern species.",
  ),
  "Berberis vulgaris.": PlantData(
    scientificName: "Berberis vulgaris",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Gewöhnliche Berberitze",
    distribution: "ToBeDone",
    totalPlanted: 83,
    maxSizeMeters: "Typically 2-3 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands and hedgerows.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common barberry is known for its spiny branches.",
  ),
  "Betula pendula.": PlantData(
    scientificName: "Betula pendula",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Hängebirke",
    distribution: "ToBeDone",
    totalPlanted: 81,
    maxSizeMeters: "Usually 15-25 meters.",
    lifeExpectancyYears: "Up to 100 years.",
    frequency: "Common.",
    habitat: "Woodlands and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Silver birch is valued for its slender, drooping branches.",
  ),
  "Betula pubescens.": PlantData(
    scientificName: "Betula pubescens",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Moor-Birke",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "Typically 15-25 meters.",
    lifeExpectancyYears: "Up to 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, heathlands, and moors.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Downy birch is more tolerant of wetter conditions than silver birch.",
  ),
  "Brachypodium sylvaticum.": PlantData(
    scientificName: "Brachypodium sylvaticum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Wald-Zwenke",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Can reach 1 meter.",
    lifeExpectancyYears: "Around 1-3 years.",
    frequency: "Common.",
    habitat: "Woodlands and grasslands.",
    leafType: "Grass, not applicable.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "False brome is a common grass species in woodland areas.",
  ),
  "Carex brizoides.": PlantData(
    scientificName: "Carex brizoides",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Zittergras-Segge",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 30-60 cm.",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and wetlands.",
    leafType: "Grass, not applicable.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common quaking grass is known for its distinctive nodding flowerheads.",
  ),
  "Carpinus betulus.": PlantData(
    scientificName: "Carpinus betulus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Hainbuche",
    distribution: "ToBeDone",
    totalPlanted: 354,
    maxSizeMeters: "Usually 15-25 meters.",
    lifeExpectancyYears: "Up to 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Hornbeam is often used for hedging and screening.",
  ),
  "Cornus sanguinea.": PlantData(
    scientificName: "Cornus sanguinea",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Blutroter Hartriegel",
    distribution: "ToBeDone",
    totalPlanted: 133,
    maxSizeMeters: "Typically 1.5-3 meters.",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Woodlands, scrub, and hedgerows.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common dogwood has distinctive red stems in winter.",
  ),
  "Corylus avellana.": PlantData(
    scientificName: "Corylus avellana",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Hasel",
    distribution: "ToBeDone",
    totalPlanted: 218,
    maxSizeMeters: "Typically 3-8 meters.",
    lifeExpectancyYears: "Up to 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "January to April.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common hazel produces edible nuts.",
  ),
  "Crataegus laevigata agg..": PlantData(
    scientificName: "Crataegus laevigata agg.",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Zweigriffeliger Weißdorn",
    distribution: "ToBeDone",
    totalPlanted: 35,
    maxSizeMeters: "Typically 5-8 meters.",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Midland hawthorn is part of a complex group of hawthorn species.",
  ),
  "Crataegus monogyna.": PlantData(
    scientificName: "Crataegus monogyna",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Weißdorn",
    distribution: "ToBeDone",
    totalPlanted: 60,
    maxSizeMeters: "Typically 5-10 meters.",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common hawthorn has thorny branches and clusters of white flowers.",
  ),
  "Cytisus Scoparius.": PlantData(
    scientificName: "Cytisus Scoparius",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Besen Ginster",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "Typically 1-3 meters.",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Heaths, open woodlands, and disturbed areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common broom is known for its bright yellow flowers.",
  ),
  "Euonymus europaeus.": PlantData(
    scientificName: "Euonymus europaeus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "europ. Pfaffenhütchen",
    distribution: "ToBeDone",
    totalPlanted: 93,
    maxSizeMeters: "Typically 2-6 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "European spindle produces striking pink fruit capsules.",
  ),
  "Fagus sylvatica.": PlantData(
    scientificName: "Fagus sylvatica",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Buche",
    distribution: "ToBeDone",
    totalPlanted: 354,
    maxSizeMeters: "Typically 25-35 meters.",
    lifeExpectancyYears: "Up to 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, often forming pure stands.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "European beech is known for its smooth, silver-gray bark.",
  ),
  "Frangula alnus.": PlantData(
    scientificName: "Frangula alnus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Faulbaum",
    distribution: "ToBeDone",
    totalPlanted: 163,
    maxSizeMeters: "Usually 2-6 meters.",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Wetlands, riverbanks, and woodlands.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Alder buckthorn is the larval food plant for brimstone butterflies.",
  ),
  "Fraxinus Excelsior.": PlantData(
    scientificName: "Fraxinus Excelsior",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Esche",
    distribution: "ToBeDone",
    totalPlanted: 143,
    maxSizeMeters: "Typically 25-35 meters.",
    lifeExpectancyYears: "Up to 200 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common ash is threatened by ash dieback disease.",
  ),
  "Fraxinus excelsior.": PlantData(
    scientificName: "Fraxinus excelsior",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Esche",
    distribution: "ToBeDone",
    totalPlanted: 180,
    maxSizeMeters: "Typically 25-35 meters.",
    lifeExpectancyYears: "Up to 200 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common ash is threatened by ash dieback disease.",
  ),
  "Galium odoratum.": PlantData(
    scientificName: "Galium odoratum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Waldmeister",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 10-50 cm.",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands and shady areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Sweet woodruff is valued for its sweet-scented flowers and leaves.",
  ),
  "Galium sylvaticum.": PlantData(
    scientificName: "Galium sylvaticum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Wald-Labkraut",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 30-60 cm.",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Wood bedstraw is often found in shady places.",
  ),
  "Ilex aquifolium.": PlantData(
    scientificName: "Ilex aquifolium",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Stechpalme",
    distribution: "ToBeDone",
    totalPlanted: 105,
    maxSizeMeters: "Typically 10-25 meters.",
    lifeExpectancyYears: "Up to 300 years.",
    frequency: "Common.",
    habitat: "Woodlands and hedgerows.",
    leafType: "Evergreen.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common holly is associated with winter festivities.",
  ),
  "Impatiens noli-tangere.": PlantData(
    scientificName: "Impatiens noli-tangere",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Großes Springkraut",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 10-40 cm.",
    lifeExpectancyYears: "Around 1-2 years.",
    frequency: "Common.",
    habitat: "Woodlands and damp areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to October.",
    conservationStatus: "Least Concern.",
    interestingFact: "Touch-me-not has explosive seed capsules.",
  ),
  "Lamium galeobdolon.": PlantData(
    scientificName: "Lamium galeobdolon",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Goldnessel",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "Typically 10-50 cm.",
    lifeExpectancyYears: "Around 5 years.",
    frequency: "Common.",
    habitat: "Woodlands and shady places.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Yellow archangel is known for its yellow flowers and square stems.",
  ),
  "Larix decidua var. polonica.": PlantData(
    scientificName: "Larix decidua var. polonica",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Polnische Lärche",
    distribution: "ToBeDone",
    totalPlanted: 71,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Up to 500 years.",
    frequency: "Common.",
    habitat: "Alpine and subalpine zones.",
    leafType: "Deciduous (needle-like leaves).",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Polish larch is a deciduous conifer.",
  ),
  "Lonicera periclymenum.": PlantData(
    scientificName: "Lonicera periclymenum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Wald-Geißblatt",
    distribution: "ToBeDone",
    totalPlanted: 35,
    maxSizeMeters: "Typically 3-6 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common honeysuckle has fragrant, tubular flowers.",
  ),
  "Malus sylvestris.": PlantData(
    scientificName: "Malus sylvestris",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Wild Apfel",
    distribution: "ToBeDone",
    totalPlanted: 91,
    maxSizeMeters: "Typically 5-10 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wild apple is the ancestor of many cultivated apple varieties.",
  ),
  "Oxalis acetosella.": PlantData(
    scientificName: "Oxalis acetosella",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Sauerklee",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 10-20 cm.",
    lifeExpectancyYears: "Around 5 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and damp areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wood sorrel's leaves fold up at night and in low light conditions.",
  ),
  "Pinus sylvestris.": PlantData(
    scientificName: "Pinus sylvestris",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Waldkiefer",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "Typically 20-35 meters.",
    lifeExpectancyYears: "Up to 500 years.",
    frequency: "Common.",
    habitat: "Woodlands, heathlands, and sandy areas.",
    leafType: "Evergreen (needle-like leaves).",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Scots pine is the national tree of Scotland.",
  ),
  "Poa nemoralis.": PlantData(
    scientificName: "Poa nemoralis",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Hain-Rispengras",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 20-60 cm.",
    lifeExpectancyYears: "Around 1-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Grass, not applicable.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wood meadow grass is a common grass in woodland habitats.",
  ),
  "Populus tremula.": PlantData(
    scientificName: "Populus tremula",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Zitterpappel",
    distribution: "ToBeDone",
    totalPlanted: 115,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, open areas, and riverbanks.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common aspen has leaves that flutter in the wind due to flattened petioles.",
  ),
  "Potentilla sterilis.": PlantData(
    scientificName: "Potentilla sterilis",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Erdbeer-Fingerkraut",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 10-30 cm.",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to August.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Barren strawberry produces small, strawberry-like fruits.",
  ),
  "Prunus Padus.": PlantData(
    scientificName: "Prunus Padus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Traubenkirsche",
    distribution: "ToBeDone",
    totalPlanted: 121,
    maxSizeMeters: "Typically 8-15 meters.",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Bird cherry is known for its fragrant, drooping flower clusters.",
  ),
  "Prunus Spinosa.": PlantData(
    scientificName: "Prunus Spinosa",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Schlehe",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "Typically 2-4 meters.",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Blackthorn is the host plant for the caterpillars of several butterfly species.",
  ),
  "Prunus avium.": PlantData(
    scientificName: "Prunus avium",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Vogel-Kische",
    distribution: "ToBeDone",
    totalPlanted: 142,
    maxSizeMeters: "Typically 15-25 meters.",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "March to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wild cherry is the ancestor of many cultivated cherry varieties.",
  ),
  "Prunus cerasifera.": PlantData(
    scientificName: "Prunus cerasifera",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Kirschpflaume",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "Typically 2-6 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Cherry plum is often cultivated for its ornamental value and edible fruits.",
  ),
  "Prunus spinosa.": PlantData(
    scientificName: "Prunus spinosa",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Schlehe",
    distribution: "ToBeDone",
    totalPlanted: 65,
    maxSizeMeters: "Typically 2-4 meters.",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Blackthorn is the host plant for the caterpillars of several butterfly species.",
  ),
  "Pyrus pyraster.": PlantData(
    scientificName: "Pyrus pyraster",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Wild-Birne",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "Typically 10-20 meters.",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Wild pear is native to Europe and Western Asia.",
  ),
  "Pyrus pyraster agg..": PlantData(
    scientificName: "Pyrus pyraster agg.",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Wild Birne",
    distribution: "ToBeDone",
    totalPlanted: 91,
    maxSizeMeters: "Typically 10-20 meters.",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "The Pyrus pyraster aggregate includes several wild pear species.",
  ),
  "Quercus patrea.": PlantData(
    scientificName: "Quercus patrea",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumnart",
    commonName: "Traubeneiche",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "Typically 15-25 meters.",
    lifeExpectancyYears: "Around 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, mixed forests, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Sessile oak is one of the native oaks in the British Isles.",
  ),
  "Quercus petraea.": PlantData(
    scientificName: "Quercus petraea",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Traubeneiche",
    distribution: "ToBeDone",
    totalPlanted: 194,
    maxSizeMeters: "Typically 20-40 meters.",
    lifeExpectancyYears: "Around 500 years.",
    frequency: "Common.",
    habitat: "Woodlands, mixed forests, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Commonly known as sessile oak, it lacks the acorn stalk found in pedunculate oak.",
  ),
  "Quercus robur.": PlantData(
    scientificName: "Quercus robur",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Stieleiche",
    distribution: "ToBeDone",
    totalPlanted: 274,
    maxSizeMeters: "Typically 20-40 meters.",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, mixed forests, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Pedunculate oak is a long-lived species with significant cultural and ecological importance.",
  ),
  "Rhammus cathartica.": PlantData(
    scientificName: "Rhammus cathartica",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Kreuzdorn",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "Typically 2-6 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common buckthorn is the larval host for the brimstone butterfly.",
  ),
  "Rhamnus frangula.": PlantData(
    scientificName: "Rhamnus frangula",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Faulbaum",
    distribution: "ToBeDone",
    totalPlanted: 63,
    maxSizeMeters: "Typically 2-6 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Alder buckthorn is the larval food plant for brimstone butterflies.",
  ),
  "Ribes rubrum.": PlantData(
    scientificName: "Ribes rubrum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Rote Johannisbeere",
    distribution: "ToBeDone",
    totalPlanted: 75,
    maxSizeMeters: "Typically 1-2 meters.",
    lifeExpectancyYears: "Around 15 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Red currant is cultivated for its edible berries.",
  ),
  "Ribes rubrum s. str..": PlantData(
    scientificName: "Ribes rubrum s. str.",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Rote Johannisbeere",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "Typically 1-2 meters.",
    lifeExpectancyYears: "Around 15 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "This refers to the strict sense (s. str.) of red currant.",
  ),
  "Rosa arvensis.": PlantData(
    scientificName: "Rosa arvensis",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Feld-Rose",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "Typically 1-3 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Field rose is known for its fragrant flowers.",
  ),
  "Rosa canina agg..": PlantData(
    scientificName: "Rosa canina agg.",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Hunds-Rose",
    distribution: "ToBeDone",
    totalPlanted: 83,
    maxSizeMeters: "Typically 1-3 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Dog rose is the most common wild rose species.",
  ),
  "Rubus caesius.": PlantData(
    scientificName: "Rubus caesius",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Kratzbeere",
    distribution: "ToBeDone",
    totalPlanted: 30,
    maxSizeMeters: "Typically 0.5-1.5 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact: "Dewberry is a low-growing relative of the blackberry.",
  ),
  "Rubus idaeus.": PlantData(
    scientificName: "Rubus idaeus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Himbeere",
    distribution: "ToBeDone",
    totalPlanted: 243,
    maxSizeMeters: "Typically 1-2 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact: "Raspberry is well-known for its delicious red berries.",
  ),
  "Rubus sect. Rubus.": PlantData(
    scientificName: "Rubus sect. Rubus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Brombeere",
    distribution: "ToBeDone",
    totalPlanted: 65,
    maxSizeMeters: "Typically 1-3 meters.",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "This refers to the section (sect.) of the Rubus genus, which includes many bramble species.",
  ),
  "Salix alba.": PlantData(
    scientificName: "Salix alba",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Silberweide",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "Typically 10-25 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Riverbanks, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "White willow is the source of salicylic acid, a precursor to aspirin.",
  ),
  "Salix aurita.": PlantData(
    scientificName: "Salix aurita",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Ohr-Weide",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "Typically 1-4 meters.",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Riverbanks, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Eared willow is named for its distinctive ear-shaped stipules.",
  ),
  "Salix caprea.": PlantData(
    scientificName: "Salix caprea",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Salweide",
    distribution: "ToBeDone",
    totalPlanted: 65,
    maxSizeMeters: "Typically 4-10 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Goat willow is an important early source of nectar for bees.",
  ),
  "Salix purpurea.": PlantData(
    scientificName: "Salix purpurea",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Purpur-Weide",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "Typically 2-6 meters.",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Riverbanks, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Purple willow is known for its purple stems in winter.",
  ),
  "Sambucus Nigra.": PlantData(
    scientificName: "Sambucus Nigra",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Schwarzer Holunder",
    distribution: "ToBeDone",
    totalPlanted: 91,
    maxSizeMeters: "Typically 3-6 meters.",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common elder has clusters of small, creamy-white flowers and dark berries.",
  ),
  "Sambucus nigra.": PlantData(
    scientificName: "Sambucus nigra",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Schwarzer Holunder",
    distribution: "ToBeDone",
    totalPlanted: 110,
    maxSizeMeters: "Typically 3-6 meters.",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Black elder is known for its use in traditional medicine and as a flavoring in beverages.",
  ),
  "Sambucus racemosa.": PlantData(
    scientificName: "Sambucus racemosa",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Roter Holunder",
    distribution: "ToBeDone",
    totalPlanted: 30,
    maxSizeMeters: "Typically 2-4 meters.",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact: "Red elderberry produces clusters of small red berries.",
  ),
  "Sorbus aucuparia.": PlantData(
    scientificName: "Sorbus aucuparia",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Eberesche",
    distribution: "ToBeDone",
    totalPlanted: 166,
    maxSizeMeters: "Typically 5-12 meters.",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Rowan is often associated with folklore and has symbolic importance.",
  ),
  "Sorbus torminalis.": PlantData(
    scientificName: "Sorbus torminalis",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Elsbeere",
    distribution: "ToBeDone",
    totalPlanted: 176,
    maxSizeMeters: "Typically 10-20 meters.",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wild service tree has distinctive lobed leaves and small fruits.",
  ),
  "Stellaria holostea.": PlantData(
    scientificName: "Stellaria holostea",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Große Steinmiere",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "Typically 30-60 cm.",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Adder's tongue spearwort has star-shaped white flowers.",
  ),
  "Taxus baccata.": PlantData(
    scientificName: "Taxus baccata",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Europäische Eibe",
    distribution: "ToBeDone",
    totalPlanted: 70,
    maxSizeMeters: "Typically 15-20 meters.",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Evergreen (needle-like leaves).",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common yew is often associated with ancient churchyards.",
  ),
  "Tilia Cordata.": PlantData(
    scientificName: "Tilia Cordata",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Winterlinde",
    distribution: "ToBeDone",
    totalPlanted: 163,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Small-leaved lime is valued for its fragrant flowers and heart-shaped leaves.",
  ),
  "Tilia cordata.": PlantData(
    scientificName: "Tilia cordata",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Winterlinde",
    distribution: "ToBeDone",
    totalPlanted: 85,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Small-leaved lime is valued for its fragrant flowers and heart-shaped leaves.",
  ),
  "Tilia platyphyllos.": PlantData(
    scientificName: "Tilia platyphyllos",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Sommerlinde",
    distribution: "ToBeDone",
    totalPlanted: 95,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Large-leaved lime has larger leaves compared to small-leaved lime.",
  ),
  "Tilia tomentosa.": PlantData(
    scientificName: "Tilia tomentosa",
    pathPicture: "./images/trees/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Silberlinde",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Silver lime has silvery-white hairs on the underside of its leaves.",
  ),
  "Ulmus glabra.": PlantData(
    scientificName: "Ulmus glabra",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Berg-Ulme",
    distribution: "ToBeDone",
    totalPlanted: 71,
    maxSizeMeters: "Typically 25-35 meters.",
    lifeExpectancyYears: "Around 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wych elm is the only elm species native to the British Isles.",
  ),
  "Ulmus laevis.": PlantData(
    scientificName: "Ulmus laevis",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Flatterulme",
    distribution: "ToBeDone",
    totalPlanted: 186,
    maxSizeMeters: "Typically 25-35 meters.",
    lifeExpectancyYears: "Around 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact: "European white elm is known for its smooth, grey bark.",
  ),
  "Ulmus minor.": PlantData(
    scientificName: "Ulmus minor",
    pathPicture: "./images/trees/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Feldulme",
    distribution: "ToBeDone",
    totalPlanted: 111,
    maxSizeMeters: "Typically 20-30 meters.",
    lifeExpectancyYears: "Around 200 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact: "Field elm is susceptible to Dutch elm disease.",
  ),
  "Vaccinium corymbosum.": PlantData(
    scientificName: "Vaccinium corymbosum",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Heidelbeere",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 1-3 meters.",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Woodlands, heathlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Highbush blueberry is cultivated for its edible berries.",
  ),
  "Viburnum opulus.": PlantData(
    scientificName: "Viburnum opulus",
    pathPicture: "./images/trees/Default.png",
    plantType: "Strauch",
    commonName: "Schneeball",
    distribution: "ToBeDone",
    totalPlanted: 123,
    maxSizeMeters: "Typically 2-5 meters.",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Guelder rose has clusters of white flowers and bright red berries.",
  ),
  "Viola reichenbachiana.": PlantData(
    scientificName: "Viola reichenbachiana",
    pathPicture: "./images/trees/Default.png",
    plantType: "Bodendecker",
    commonName: "Wald-Veilchen",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "Typically 10-20 cm.",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Early dog-violet is one of the first violets to bloom in spring.",
  ),
};
