// this is the biggest data file defining the PlantData class and holding a Map of the most common and some rare european trees and bushes,
// it shall also include herbs and every plant species used in the tiny forest project

class PlantData {
  final String scientificName;
  final String commonName;
  final String commonNameEn;
  final String commonNameDe;
  final String commonNameEs;
  String pathPicture;
  final String plantType;
  String distribution;
  final String maxSizeMeters;
  final int totalPlanted;
  int localPlanted;

  final String lifeExpectancyYears;
  final String frequency;
  final String habitat;
  final String leafType;
  final String floweringSeason;
  final String conservationStatus;
  final String interestingFact;

  PlantData(
      {required this.scientificName,
      required this.commonName,
      required this.commonNameEn,
      required this.commonNameDe,
      required this.commonNameEs,
      required this.distribution,
      required this.maxSizeMeters,
      required this.totalPlanted,
      required this.localPlanted,
      required this.lifeExpectancyYears,
      required this.frequency,
      required this.habitat,
      required this.leafType,
      required this.floweringSeason,
      required this.conservationStatus,
      required this.interestingFact,
      required this.pathPicture,
      required this.plantType});

  @override
  String toString() {
    return 'PlantData(\n'
        '  scientificName: "$scientificName",\n'
        '  commonName: "$commonName",\n'
        '  commonNameEn: "$commonNameEn",\n'
        '  commonNameDe: "$commonNameDe",\n'
        '  commonNameEs: "$commonNameEs",\n'
        '  distribution: "$distribution",\n'
        '  maxSizeMeters: "$maxSizeMeters",\n'
        '  totalPlanted: $totalPlanted,\n'
        '  localPlanted: $localPlanted,\n'
        '  lifeExpectancyYears: "$lifeExpectancyYears",\n'
        '  frequency: "$frequency",\n'
        '  habitat: "$habitat",\n'
        '  leafType: "$leafType",\n'
        '  floweringSeason: "$floweringSeason",\n'
        '  conservationStatus: "$conservationStatus",\n'
        '  interestingFact: "$interestingFact",\n'
        '  pathPicture: "$pathPicture",\n'
        '  plantType: "$plantType"\n'
        ')';
  }
}

Map<String, PlantData> allPlants = {
  "Acer campestre": PlantData(
      scientificName: "Acer campestre",
      commonName: "Feldahorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. Asia",
      maxSizeMeters: "10-15",
      totalPlanted: 141,
      localPlanted: 1,
      lifeExpectancyYears: "Approximately 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and parks.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact: "The field maple has distinctive three-lobed leaves.",
      pathPicture: "images/plants/Acer campestre.jpeg",
      plantType: "Nebenbaumart"),
  "Acer monspessulanum": PlantData(
      scientificName: "Acer monspessulanum",
      commonName: "Felsenahorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "S. Europe, N. Africa, W. Asia",
      maxSizeMeters: "10",
      totalPlanted: 40,
      localPlanted: 1,
      lifeExpectancyYears: "About 100 years.",
      frequency: "Common in its range.",
      habitat: "Dry woods and rocky places.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Also known as Montpellier maple, it's native to the Mediterranean region.",
      pathPicture: "images/plants/Acer monspessulanum.jpeg",
      plantType: "Nebenbaumart"),
  "Acer platanoides": PlantData(
      scientificName: "Acer platanoides",
      commonName: "Spitz-Ahorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. Asia",
      maxSizeMeters: "20-25",
      totalPlanted: 110,
      localPlanted: 1,
      lifeExpectancyYears: "Around 250 years.",
      frequency: "Common.",
      habitat: "Various, often in urban areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Norway maple is valued for its shade and attractive foliage.",
      pathPicture: "images/plants/Acer platanoides.jpeg",
      plantType: "Hauptbaumart"),
  "Acer pseudoplatanus": PlantData(
      scientificName: "Acer pseudoplatanus",
      commonName: "Bergahorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. Asia",
      maxSizeMeters: "40",
      totalPlanted: 345,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 400 years.",
      frequency: "Common.",
      habitat: "Woodlands and mixed forests.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Sycamore maple is known for its large, palmately lobed leaves.",
      pathPicture: "images/plants/Acer pseudoplatanus.jpeg",
      plantType: "Hauptbaumart"),
  "Alnus glutinosa": PlantData(
      scientificName: "Alnus glutinosa",
      commonName: "Schwarzerle",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "20-25",
      totalPlanted: 50,
      localPlanted: 1,
      lifeExpectancyYears: "Around 60 years.",
      frequency: "Common.",
      habitat: "Wetlands and riverbanks.",
      leafType: "Deciduous.",
      floweringSeason: "February to March.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Common alder is associated with wet or waterlogged soils.",
      pathPicture: "images/plants/Alnus glutinosa.jpeg",
      plantType: "Hauptbaumart"),
  "Amelanchier ovalis": PlantData(
      scientificName: "Amelanchier ovalis",
      commonName: "Gewöhnliche Felsenbirne",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "3-8",
      totalPlanted: 63,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 50 years.",
      frequency: "Common.",
      habitat: "Woodlands and heathlands.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact: "Serviceberries produce edible berries.",
      pathPicture: "images/plants/Amelanchier ovalis.jpeg",
      plantType: "Strauch"),
  "Anemone nemorosa": PlantData(
      scientificName: "Anemone nemorosa",
      commonName: "Buschwindröschen",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.1-0.3",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "About 50 years.",
      frequency: "Common.",
      habitat: "Woodlands and meadows.",
      leafType: "Deciduous.",
      floweringSeason: "March to May.",
      conservationStatus: "Vulnerable",
      interestingFact: "Also known as wood anemone, it spreads by rhizomes.",
      pathPicture: "images/plants/Anemone nemorosa.jpeg",
      plantType: "Bodendecker"),
  "Athyrium filix-femina": PlantData(
      scientificName: "Athyrium filix-femina",
      commonName: "Wald-Frauenfarn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Temperate regions of N. Hemisphere",
      maxSizeMeters: "1",
      totalPlanted: 50,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 100 years.",
      frequency: "Common.",
      habitat: "Woodlands and shady areas.",
      leafType: "Deciduous.",
      floweringSeason: "Not applicable (fern).",
      conservationStatus: "Least Concern",
      interestingFact: "Lady fern is a common woodland fern species.",
      pathPicture: "images/plants/Athyrium filix-femina.jpeg",
      plantType: "Bodendecker"),
  "Berberis vulgaris": PlantData(
      scientificName: "Berberis vulgaris",
      commonName: "Gewöhnliche Berberitze",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-3",
      totalPlanted: 83,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands and hedgerows.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Near Threatened",
      interestingFact: "Common barberry is known for its spiny branches.",
      pathPicture: "images/plants/Berberis vulgaris.jpeg",
      plantType: "Strauch"),
  "Betula pendula": PlantData(
      scientificName: "Betula pendula",
      commonName: "Hängebirke",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "15-25",
      totalPlanted: 81,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 100 years.",
      frequency: "Common.",
      habitat: "Woodlands and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Silver birch is valued for its slender, drooping branches.",
      pathPicture: "images/plants/Betula pendula.jpeg",
      plantType: "Nebenbaumart"),
  "Betula pubescens": PlantData(
      scientificName: "Betula pubescens",
      commonName: "Moor-Birke",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "15-25",
      totalPlanted: 40,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, heathlands, and moors.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Downy birch is more tolerant of wetter conditions than silver birch.",
      pathPicture: "images/plants/Betula pubescens.jpeg",
      plantType: "Nebenbaumart"),
  "Brachypodium sylvaticum": PlantData(
      scientificName: "Brachypodium sylvaticum",
      commonName: "Wald-Zwenke",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1-3 years.",
      frequency: "Common.",
      habitat: "Woodlands and grasslands.",
      leafType: "Grass, not applicable.",
      floweringSeason: "June to August.",
      conservationStatus: "Least Concern",
      interestingFact:
          "False brome is a common grass species in woodland areas.",
      pathPicture: "images/plants/Brachypodium sylvaticum.jpeg",
      plantType: "Bodendecker"),
  "Carex brizoides": PlantData(
      scientificName: "Carex brizoides",
      commonName: "Zittergras-Segge",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. Asia",
      maxSizeMeters: "0.3-0.6",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 2-3 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and wetlands.",
      leafType: "Grass, not applicable.",
      floweringSeason: "May to June.",
      conservationStatus: "Endangered",
      interestingFact:
          "Common quaking grass is known for its distinctive nodding flowerheads.",
      pathPicture: "images/plants/Carex brizoides.jpeg",
      plantType: "Bodendecker"),
  "Carpinus betulus": PlantData(
      scientificName: "Carpinus betulus",
      commonName: "Hainbuche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "15-25",
      totalPlanted: 396,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 300 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and parks.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact: "Hornbeam is often used for hedging and screening.",
      pathPicture: "images/plants/Carpinus betulus.jpeg",
      plantType: "Hauptbaumart"),
  "Cornus sanguinea": PlantData(
      scientificName: "Cornus sanguinea",
      commonName: "Blutroter Hartriegel",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1.5-3",
      totalPlanted: 153,
      localPlanted: 1,
      lifeExpectancyYears: "Around 60 years.",
      frequency: "Common.",
      habitat: "Woodlands, scrub, and hedgerows.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact: "Common dogwood has distinctive red stems in winter.",
      pathPicture: "images/plants/Cornus sanguinea.jpeg",
      plantType: "Strauch"),
  "Corylus avellana": PlantData(
      scientificName: "Corylus avellana",
      commonName: "Hasel",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "3-8",
      totalPlanted: 238,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 80 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "January to April.",
      conservationStatus: "Least Concern",
      interestingFact: "Common hazel produces edible nuts.",
      pathPicture: "images/plants/Corylus avellana.jpeg",
      plantType: "Strauch"),
  "Crataegus laevigata agg": PlantData(
      scientificName: "Crataegus laevigata agg",
      commonName: "Zweigriffeliger Weißdorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. Asia",
      maxSizeMeters: "5-8",
      totalPlanted: 35,
      localPlanted: 1,
      lifeExpectancyYears: "Around 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and scrub.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Midland hawthorn is part of a complex group of hawthorn species.",
      pathPicture: "./images/plants/Crataegus laevigata.jpeg",
      plantType: "Strauch"),
  "Crataegus monogyna": PlantData(
      scientificName: "Crataegus monogyna",
      commonName: "Weißdorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "5-10",
      totalPlanted: 183,
      localPlanted: 1,
      lifeExpectancyYears: "Around 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Common hawthorn has thorny branches and clusters of white flowers.",
      pathPicture: "images/plants/Crataegus monogyna.jpeg",
      plantType: "Strauch"),
  "Cytisus scoparius": PlantData(
      scientificName: "Cytisus scoparius",
      commonName: "Besen Ginster",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "ToBeDone",
      maxSizeMeters: "1-3",
      totalPlanted: 123,
      localPlanted: 1,
      lifeExpectancyYears: "Around 30 years.",
      frequency: "Common.",
      habitat: "Heaths, open woodlands, and disturbed areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Least Concern",
      interestingFact: "Common broom is known for its bright yellow flowers.",
      pathPicture: "./images/plants/Cytisus scoparius.jpeg",
      plantType: "Strauch"),
  "Euonymus europaeus": PlantData(
      scientificName: "Euonymus europaeus",
      commonName: "europ. Pfaffenhütchen",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-6",
      totalPlanted: 93,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and scrub.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "European spindle produces striking pink fruit capsules.",
      pathPicture: "./images/plants/Euonymus europaeus.jpeg",
      plantType: "Strauch"),
  "Fagus sylvatica": PlantData(
      scientificName: "Fagus sylvatica",
      commonName: "Buche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. Asia",
      maxSizeMeters: "25-35",
      totalPlanted: 396,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 300 years.",
      frequency: "Common.",
      habitat: "Woodlands, often forming pure stands.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "European beech is known for its smooth, silver-gray bark.",
      pathPicture: "./images/plants/Fagus sylvatica.jpeg",
      plantType: "Hauptbaumart"),
  "Frangula alnus": PlantData(
      scientificName: "Frangula alnus",
      commonName: "Faulbaum",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-6",
      totalPlanted: 183,
      localPlanted: 1,
      lifeExpectancyYears: "Around 60 years.",
      frequency: "Common.",
      habitat: "Wetlands, riverbanks, and woodlands.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Alder buckthorn is the larval food plant for brimstone butterflies.",
      pathPicture: "./images/plants/Frangula alnus.jpeg",
      plantType: "Strauch"),
  "Fraxinus excelsior": PlantData(
      scientificName: "Fraxinus excelsior",
      commonName: "Esche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "25-35",
      totalPlanted: 365,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 200 years.",
      frequency: "Common.",
      habitat: "Woodlands, riverbanks, and parks.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact: "Common ash is threatened by ash dieback disease.",
      pathPicture: "./images/plants/Fraxinus excelsior.jpeg",
      plantType: "Hauptbaumart"),
  "Galium odoratum": PlantData(
      scientificName: "Galium odoratum",
      commonName: "Waldmeister",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.1-0.5",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 2-3 years.",
      frequency: "Common.",
      habitat: "Woodlands and shady areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Vulnerable",
      interestingFact:
          "Sweet woodruff is valued for its sweet-scented flowers and leaves.",
      pathPicture: "./images/plants/Galium odoratum.jpeg",
      plantType: "Bodendecker"),
  "Galium sylvaticum": PlantData(
      scientificName: "Galium sylvaticum",
      commonName: "Wald-Labkraut",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. Asia",
      maxSizeMeters: "0.3-0.6",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 2-3 years.",
      frequency: "Common.",
      habitat: "Woodlands and grassy areas.",
      leafType: "Deciduous.",
      floweringSeason: "June to August.",
      conservationStatus: "Least Concern",
      interestingFact: "Wood bedstraw is often found in shady places.",
      pathPicture: "./images/plants/Galium sylvaticum.jpeg",
      plantType: "Bodendecker"),
  "Ilex aquifolium": PlantData(
      scientificName: "Ilex aquifolium",
      commonName: "Stechpalme",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "10-25",
      totalPlanted: 125,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 300 years.",
      frequency: "Common.",
      habitat: "Woodlands and hedgerows.",
      leafType: "Evergreen.",
      floweringSeason: "May to June.",
      conservationStatus: "Near Threatened",
      interestingFact: "Common holly is associated with winter festivities.",
      pathPicture: "./images/plants/Ilex aquifolium.jpeg",
      plantType: "Strauch"),
  "Impatiens noli-tangere": PlantData(
      scientificName: "Impatiens noli-tangere",
      commonName: "Großes Springkraut",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "0.1-0.4",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1-2 years.",
      frequency: "Common.",
      habitat: "Woodlands and damp areas.",
      leafType: "Deciduous.",
      floweringSeason: "June to October.",
      conservationStatus: "Vulnerable",
      interestingFact: "Touch-me-not has explosive seed capsules.",
      pathPicture: "./images/plants/Impatiens noli-tangere.jpeg",
      plantType: "Bodendecker"),
  "Lamium galeobdolon": PlantData(
      scientificName: "Lamium galeobdolon",
      commonName: "Goldnessel",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.1-0.5",
      totalPlanted: 50,
      localPlanted: 1,
      lifeExpectancyYears: "Around 5 years.",
      frequency: "Common.",
      habitat: "Woodlands and shady places.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Yellow archangel is known for its yellow flowers and square stems.",
      pathPicture: "./images/plants/Lamium galeobdolon.jpeg",
      plantType: "Bodendecker"),
  "Larix decidua": PlantData(
      scientificName: "Larix decidua",
      commonName: "Polnische Lärche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "ToBeDone",
      maxSizeMeters: "20-30",
      totalPlanted: 71,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 500 years.",
      frequency: "Common.",
      habitat: "Alpine and subalpine zones.",
      leafType: "Deciduous (needle-like leaves).",
      floweringSeason: "May to June.",
      conservationStatus: "Critically Endangered ",
      interestingFact: "Polish larch is a deciduous conifer.",
      pathPicture: "./images/plants/Larix decidua.jpeg",
      plantType: "Nebenbaumart"),
  "Lonicera periclymenum": PlantData(
      scientificName: "Lonicera periclymenum",
      commonName: "Wald-Geißblatt",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "3-6",
      totalPlanted: 35,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and scrub.",
      leafType: "Deciduous.",
      floweringSeason: "June to August.",
      conservationStatus: "Least Concern",
      interestingFact: "Common honeysuckle has fragrant, tubular flowers.",
      pathPicture: "./images/plants/Lonicera periclymenum.jpeg",
      plantType: "Strauch"),
  "Malus sylvestris": PlantData(
      scientificName: "Malus sylvestris",
      commonName: "Wild Apfel",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "5-10",
      totalPlanted: 111,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Vulnerable",
      interestingFact:
          "Wild apple is the ancestor of many cultivated apple varieties.",
      pathPicture: "images/plants/Malus sylvestris.jpeg",
      plantType: "Nebenbaumart"),
  "Oxalis acetosella": PlantData(
      scientificName: "Oxalis acetosella",
      commonName: "Sauerklee",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.1-0.2",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 5 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and damp areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Wood sorrel's leaves fold up at night and in low light conditions.",
      pathPicture: "images/plants/Oxalis acetosella.jpeg",
      plantType: "Bodendecker"),
  "Pinus sylvestris": PlantData(
      scientificName: "Pinus sylvestris",
      commonName: "Waldkiefer",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "20-35",
      totalPlanted: 111,
      localPlanted: 1,
      lifeExpectancyYears: "Up to 500 years.",
      frequency: "Common.",
      habitat: "Woodlands, heathlands, and sandy areas.",
      leafType: "Evergreen (needle-like leaves).",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact: "Scots pine is the national tree of Scotland.",
      pathPicture: "images/plants/Pinus sylvestris.jpeg",
      plantType: "Nebenbaumart"),
  "Poa nemoralis": PlantData(
      scientificName: "Poa nemoralis",
      commonName: "Hain-Rispengras",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.2-0.6",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1-3 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and grassy areas.",
      leafType: "Grass, not applicable.",
      floweringSeason: "May to July.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Wood meadow grass is a common grass in woodland habitats.",
      pathPicture: "images/plants/Poa nemoralis.jpeg",
      plantType: "Bodendecker"),
  "Populus tremula": PlantData(
      scientificName: "Populus tremula",
      commonName: "Zitterpappel",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "20-30",
      totalPlanted: 115,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, open areas, and riverbanks.",
      leafType: "Deciduous.",
      floweringSeason: "March to April.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Common aspen has leaves that flutter in the wind due to flattened petioles.",
      pathPicture: "images/plants/Populus tremula.jpeg",
      plantType: "Nebenbaumart"),
  "Potentilla sterilis": PlantData(
      scientificName: "Potentilla sterilis",
      commonName: "Erdbeer-Fingerkraut",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. Asia",
      maxSizeMeters: "0.1-0.3",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 2-3 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and grassy areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to August.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Barren strawberry produces small, strawberry-like fruits.",
      pathPicture: "images/plants/Potentilla sterilis.jpeg",
      plantType: "Bodendecker"),
  "Prunus padus": PlantData(
      scientificName: "Prunus padus",
      commonName: "Traubenkirsche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "ToBeDone",
      maxSizeMeters: "8-15",
      totalPlanted: 141,
      localPlanted: 1,
      lifeExpectancyYears: "Around 60 years.",
      frequency: "Common.",
      habitat: "Woodlands, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Bird cherry is known for its fragrant, drooping flower clusters.",
      pathPicture: "./images/plants/Prunus padus.jpeg",
      plantType: "Nebenbaumart"),
  "Prunus spinosa": PlantData(
      scientificName: "Prunus spinosa",
      commonName: "Schlehe",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "ToBeDone",
      maxSizeMeters: "2-4",
      totalPlanted: 188,
      localPlanted: 1,
      lifeExpectancyYears: "Around 30 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and scrub.",
      leafType: "Deciduous.",
      floweringSeason: "March to April.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Blackthorn is the host plant for the caterpillars of several butterfly species.",
      pathPicture: "./images/plants/Prunus spinosa.jpeg",
      plantType: "Strauch"),
  "Prunus avium": PlantData(
      scientificName: "Prunus avium",
      commonName: "Vogel-Kische",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "15-25",
      totalPlanted: 162,
      localPlanted: 1,
      lifeExpectancyYears: "Around 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "March to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Wild cherry is the ancestor of many cultivated cherry varieties.",
      pathPicture: "images/plants/Prunus avium.jpeg",
      plantType: "Hauptbaumart"),
  "Prunus cerasifera": PlantData(
      scientificName: "Prunus cerasifera",
      commonName: "Kirschpflaume",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "S.E. Europe, W. Asia",
      maxSizeMeters: "2-6",
      totalPlanted: 40,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "March to April.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Cherry plum is often cultivated for its ornamental value and edible fruits.",
      pathPicture: "./images/plants/Prunus cerasifera.jpeg",
      plantType: "Strauch"),
  "Pyrus pyraster": PlantData(
      scientificName: "Pyrus pyraster",
      commonName: "Wild-Birne",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "10-20",
      totalPlanted: 40,
      localPlanted: 1,
      lifeExpectancyYears: "Around 80 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Vulnerable",
      interestingFact: "Wild pear is native to Europe and Western Asia.",
      pathPicture: "images/plants/Pyrus pyraster.jpeg",
      plantType: "Strauch"),
  "Pyrus pyraster agg": PlantData(
      scientificName: "Pyrus pyraster agg",
      commonName: "Wild Birne",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "10-20",
      totalPlanted: 111,
      localPlanted: 1,
      lifeExpectancyYears: "Around 80 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "The Pyrus pyraster aggregate includes several wild pear species.",
      pathPicture: "./images/plants/Pyrus pyraster.jpeg",
      plantType: "Nebenbaumart"),
  "Quercus petraea": PlantData(
      scientificName: "Quercus petraea",
      commonName: "Traubeneiche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. Asia",
      maxSizeMeters: "20-40",
      totalPlanted: 286,
      localPlanted: 1,
      lifeExpectancyYears: "Around 500 years.",
      frequency: "Common.",
      habitat: "Woodlands, mixed forests, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Commonly known as sessile oak, it lacks the acorn stalk found in pedunculate oak.",
      pathPicture: "./images/plants/Quercus petraea.jpeg",
      plantType: "Nebenbaumart"),
  "Quercus robur": PlantData(
      scientificName: "Quercus robur",
      commonName: "Stieleiche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "20-40",
      totalPlanted: 316,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1,000 years.",
      frequency: "Common.",
      habitat: "Woodlands, mixed forests, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Pedunculate oak is a long-lived species with significant cultural and ecological importance.",
      pathPicture: "./images/plants/Quercus robur.jpeg",
      plantType: "Nebenbaumart"),
  "Rhamnus cathartica": PlantData(
      scientificName: "Rhamnus cathartica",
      commonName: "Kreuzdorn",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-6",
      totalPlanted: 123,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Common buckthorn is the larval host for the brimstone butterfly.",
      pathPicture: "images/plants/Rhamnus cathartica.jpeg",
      plantType: "Strauch"),
  "Rhamnus frangula": PlantData(
      scientificName: "Rhamnus frangula",
      commonName: "Faulbaum",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-6",
      totalPlanted: 63,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Alder buckthorn is the larval food plant for brimstone butterflies.",
      pathPicture: "images/plants/Rhamnus frangula.jpeg",
      plantType: "Strauch"),
  "Ribes rubrum": PlantData(
      scientificName: "Ribes rubrum",
      commonName: "Rote Johannisbeere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1-2",
      totalPlanted: 198,
      localPlanted: 1,
      lifeExpectancyYears: "Around 15 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Vulnerable",
      interestingFact: "Red currant is cultivated for its edible berries.",
      pathPicture: "./images/plants/Ribes rubrum.jpeg",
      plantType: "Strauch"),
  "Rosa arvensis": PlantData(
      scientificName: "Rosa arvensis",
      commonName: "Feld-Rose",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1-3",
      totalPlanted: 20,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "June to August.",
      conservationStatus: "Least Concern",
      interestingFact: "Field rose is known for its fragrant flowers.",
      pathPicture: "images/plants/Rosa arvensis.jpeg",
      plantType: "Strauch"),
  "Rosa canina agg": PlantData(
      scientificName: "Rosa canina agg",
      commonName: "Hunds-Rose",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1-3",
      totalPlanted: 103,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "June to August.",
      conservationStatus: "Least Concern",
      interestingFact: "Dog rose is the most common wild rose species.",
      pathPicture: "./images/plants/Rosa canina.jpeg",
      plantType: "Strauch"),
  "Rubus caesius": PlantData(
      scientificName: "Rubus caesius",
      commonName: "Kratzbeere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.5-1.5",
      totalPlanted: 30,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to July.",
      conservationStatus: "Least Concern",
      interestingFact: "Dewberry is a low-growing relative of the blackberry.",
      pathPicture: "./images/plants/Rubus caesius.jpeg",
      plantType: "Strauch"),
  "Rubus idaeus": PlantData(
      scientificName: "Rubus idaeus",
      commonName: "Himbeere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1-2",
      totalPlanted: 263,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to July.",
      conservationStatus: "Least Concern",
      interestingFact: "Raspberry is well-known for its delicious red berries.",
      pathPicture: "./images/plants/Rubus idaeus.jpeg",
      plantType: "Strauch"),
  "Rubus sect. Rubus": PlantData(
      scientificName: "Rubus sect. Rubus",
      commonName: "Brombeere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1-3",
      totalPlanted: 65,
      localPlanted: 1,
      lifeExpectancyYears: "Around 20 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to July.",
      conservationStatus: "Least Concern",
      interestingFact:
          "This refers to the section (sect.) of the Rubus genus, which includes many bramble species.",
      pathPicture: "./images/plants/Rubus idaeus.jpeg",
      plantType: "Strauch"),
  "Salix alba": PlantData(
      scientificName: "Salix alba",
      commonName: "Silberweide",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "10-25",
      totalPlanted: 20,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Riverbanks, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "White willow is the source of salicylic acid, a precursor to aspirin.",
      pathPicture: "./images/plants/Salix alba.jpeg",
      plantType: "Nebenbaumart"),
  "Salix aurita": PlantData(
      scientificName: "Salix aurita",
      commonName: "Ohr-Weide",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "1-4",
      totalPlanted: 20,
      localPlanted: 1,
      lifeExpectancyYears: "Around 30 years.",
      frequency: "Common.",
      habitat: "Riverbanks, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Eared willow is named for its distinctive ear-shaped stipules.",
      pathPicture: "./images/plants/Salix aurita.jpeg",
      plantType: "Strauch"),
  "Salix caprea": PlantData(
      scientificName: "Salix caprea",
      commonName: "Salweide",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "4-10",
      totalPlanted: 65,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "March to April.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Goat willow is an important early source of nectar for bees.",
      pathPicture: "./images/plants/Salix caprea.jpeg",
      plantType: "Nebenbaumart"),
  "Salix purpurea": PlantData(
      scientificName: "Salix purpurea",
      commonName: "Purpur-Weide",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-6",
      totalPlanted: 123,
      localPlanted: 1,
      lifeExpectancyYears: "Around 30 years.",
      frequency: "Common.",
      habitat: "Riverbanks, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to May.",
      conservationStatus: "Least Concern",
      interestingFact: "Purple willow is known for its purple stems in winter.",
      pathPicture: "images/plants/Salix purpurea.jpeg",
      plantType: "Strauch"),
  "Sambucus nigra": PlantData(
      scientificName: "Sambucus nigra",
      commonName: "Schwarzer Holunder",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "ToBeDone",
      maxSizeMeters: "3-6",
      totalPlanted: 221,
      localPlanted: 1,
      lifeExpectancyYears: "Around 80 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "June to July.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Black elder is known for its use in traditional medicine and as a flavoring in beverages.",
      pathPicture: "./images/plants/Sambucus nigra.jpeg",
      plantType: "Strauch"),
  "Sambucus racemosa": PlantData(
      scientificName: "Sambucus racemosa",
      commonName: "Roter Holunder",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-4",
      totalPlanted: 30,
      localPlanted: 1,
      lifeExpectancyYears: "Around 50 years.",
      frequency: "Common.",
      habitat: "Woodlands, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "June to July.",
      conservationStatus: "Least Concern",
      interestingFact: "Red elderberry produces clusters of small red berries.",
      pathPicture: "images/plants/Sambucus racemosa.jpeg",
      plantType: "Strauch"),
  "Sorbus aucuparia": PlantData(
      scientificName: "Sorbus aucuparia",
      commonName: "Eberesche",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "5-12",
      totalPlanted: 186,
      localPlanted: 1,
      lifeExpectancyYears: "Around 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Rowan is often associated with folklore and has symbolic importance.",
      pathPicture: "images/plants/Sorbus aucuparia.jpeg",
      plantType: "Nebenbaumart"),
  "Sorbus torminalis": PlantData(
      scientificName: "Sorbus torminalis",
      commonName: "Elsbeere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "10-20",
      totalPlanted: 196,
      localPlanted: 1,
      lifeExpectancyYears: "Around 100 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Wild service tree has distinctive lobed leaves and small fruits.",
      pathPicture: "images/plants/Sorbus torminalis.jpeg",
      plantType: "Nebenbaumart"),
  "Stellaria holostea": PlantData(
      scientificName: "Stellaria holostea",
      commonName: "Große Steinmiere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.3-0.6",
      totalPlanted: 50,
      localPlanted: 1,
      lifeExpectancyYears: "Around 2-3 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and grassy areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Adder's tongue spearwort has star-shaped white flowers.",
      pathPicture: "images/plants/Stellaria holostea.jpeg",
      plantType: "Bodendecker"),
  "Taxus baccata": PlantData(
      scientificName: "Taxus baccata",
      commonName: "Europäische Eibe",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "15-20",
      totalPlanted: 90,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1,000 years.",
      frequency: "Common.",
      habitat: "Woodlands, hedgerows, and open areas.",
      leafType: "Evergreen (needle-like leaves).",
      floweringSeason: "March to April.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Common yew is often associated with ancient churchyards.",
      pathPicture: "images/plants/Taxus baccata.jpeg",
      plantType: "Hauptbaumart"),
  "Tilia cordata": PlantData(
      scientificName: "Tilia cordata",
      commonName: "Winterlinde",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "20-30",
      totalPlanted: 268,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1,000 years.",
      frequency: "Common.",
      habitat: "Woodlands, parks, and avenues.",
      leafType: "Deciduous.",
      floweringSeason: "June to July.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Small-leaved lime is valued for its fragrant flowers and heart-shaped leaves.",
      pathPicture: "images/plants/Tilia cordata.jpeg",
      plantType: "Hauptbaumart"),
  "Tilia platyphyllos": PlantData(
      scientificName: "Tilia platyphyllos",
      commonName: "Sommerlinde",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "20-30",
      totalPlanted: 115,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1,000 years.",
      frequency: "Common.",
      habitat: "Woodlands, parks, and avenues.",
      leafType: "Deciduous.",
      floweringSeason: "June to July.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Large-leaved lime has larger leaves compared to small-leaved lime.",
      pathPicture: "images/plants/Tilia platyphyllos.jpeg",
      plantType: "Hauptbaumart"),
  "Tilia tomentosa": PlantData(
      scientificName: "Tilia tomentosa",
      commonName: "Silberlinde",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "S.E. Europe, W. Asia",
      maxSizeMeters: "20-30",
      totalPlanted: 40,
      localPlanted: 1,
      lifeExpectancyYears: "Around 1,000 years.",
      frequency: "Common.",
      habitat: "Woodlands, parks, and avenues.",
      leafType: "Deciduous.",
      floweringSeason: "June to July.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Silver lime has silvery-white hairs on the underside of its leaves.",
      pathPicture: "images/plants/Tilia tomentosa.jpeg",
      plantType: "Hauptbaumart"),
  "Ulmus glabra": PlantData(
      scientificName: "Ulmus glabra",
      commonName: "Berg-Ulme",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "25-35",
      totalPlanted: 71,
      localPlanted: 1,
      lifeExpectancyYears: "Around 300 years.",
      frequency: "Common.",
      habitat: "Woodlands, riverbanks, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "February to March.",
      conservationStatus: "Endangered",
      interestingFact:
          "Wych elm is the only elm species native to the British Isles.",
      pathPicture: "images/plants/Ulmus glabra.jpeg",
      plantType: "Nebenbaumart"),
  "Ulmus laevis": PlantData(
      scientificName: "Ulmus laevis",
      commonName: "Flatterulme",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, W. & C. Asia",
      maxSizeMeters: "25-35",
      totalPlanted: 206,
      localPlanted: 1,
      lifeExpectancyYears: "Around 300 years.",
      frequency: "Common.",
      habitat: "Woodlands, riverbanks, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "February to March.",
      conservationStatus: "Endangered",
      interestingFact: "European white elm is known for its smooth, grey bark.",
      pathPicture: "images/plants/Ulmus laevis.jpeg",
      plantType: "Nebenbaumart"),
  "Ulmus minor": PlantData(
      scientificName: "Ulmus minor",
      commonName: "Feldulme",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "20-30",
      totalPlanted: 111,
      localPlanted: 1,
      lifeExpectancyYears: "Around 200 years.",
      frequency: "Common.",
      habitat: "Woodlands, riverbanks, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "February to March.",
      conservationStatus: "Endangered",
      interestingFact: "Field elm is susceptible to Dutch elm disease.",
      pathPicture: "images/plants/Ulmus minor.jpeg",
      plantType: "Nebenbaumart"),
  "Vaccinium corymbosum": PlantData(
      scientificName: "Vaccinium corymbosum",
      commonName: "Heidelbeere",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "E. North America",
      maxSizeMeters: "1-3",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 60 years.",
      frequency: "Common.",
      habitat: "Woodlands, heathlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Highbush blueberry is cultivated for its edible berries.",
      pathPicture: "images/plants/Vaccinium corymbosum.jpeg",
      plantType: "Bodendecker"),
  "Viburnum opulus": PlantData(
      scientificName: "Viburnum opulus",
      commonName: "Schneeball",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "2-5",
      totalPlanted: 123,
      localPlanted: 1,
      lifeExpectancyYears: "Around 80 years.",
      frequency: "Common.",
      habitat: "Woodlands, wetlands, and open areas.",
      leafType: "Deciduous.",
      floweringSeason: "May to June.",
      conservationStatus: "Near Threatened",
      interestingFact:
          "Guelder rose has clusters of white flowers and bright red berries.",
      pathPicture: "images/plants/Viburnum opulus.jpeg",
      plantType: "Strauch"),
  "Viola reichenbachiana": PlantData(
      scientificName: "Viola reichenbachiana",
      commonName: "Wald-Veilchen",
      commonNameEn: "Testing",
      commonNameDe: "Test",
      commonNameEs: "Prueba",
      distribution: "Europe, N. Africa, W. & C. Asia",
      maxSizeMeters: "0.1-0.2",
      totalPlanted: 25,
      localPlanted: 1,
      lifeExpectancyYears: "Around 2-3 years.",
      frequency: "Common.",
      habitat: "Woodlands, meadows, and grassy areas.",
      leafType: "Deciduous.",
      floweringSeason: "April to June.",
      conservationStatus: "Least Concern",
      interestingFact:
          "Early dog-violet is one of the first violets to bloom in spring.",
      pathPicture: "images/plants/Viola reichenbachiana.jpeg",
      plantType: "Bodendecker"),
};
