// this is the biggest data file defining the PlantData class and holding a Map of the most common and some rare european trees and bushes,
// it shall also include herbs and every plant species used in the tiny forest project

class PlantData {
  final String scientificName;
  final String commonName;
  String pathPicture;
  final String plantType;
  String distribution;
  final String maxSizeMeters;
  int totalPlanted;
  final String lifeExpectancyYears;
  final String frequency;
  final String habitat;
  final String leafType;
  final String floweringSeason;
  final String conservationStatus;
  final String interestingFact;

  PlantData(
      {required this.scientificName,
      required this.commonName,
      required this.distribution,
      required this.maxSizeMeters,
      required this.totalPlanted,
      required this.lifeExpectancyYears,
      required this.frequency,
      required this.habitat,
      required this.leafType,
      required this.floweringSeason,
      required this.conservationStatus,
      required this.interestingFact,
      required this.pathPicture,
      required this.plantType});
}

Map<String, PlantData> allPlants = {
  "Acer campestre": PlantData(
    scientificName: "Acer campestre",
    pathPicture: "./images/plants/Acer campestre.jpeg",
    plantType: "Nebenbaumart",
    commonName: "Feldahorn",
    distribution: "ToBeDone",
    totalPlanted: 141,
    maxSizeMeters: "10-15",
    lifeExpectancyYears: "Approximately 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "The field maple has distinctive three-lobed leaves.",
  ),
  "Acer monspessulanum": PlantData(
    scientificName: "Acer monspessulanum",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Felsenahorn",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "10",
    lifeExpectancyYears: "About 100 years.",
    frequency: "Common in its range.",
    habitat: "Dry woods and rocky places.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Also known as Montpellier maple, it's native to the Mediterranean region.",
  ),
  "Acer platanoides": PlantData(
    scientificName: "Acer platanoides",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Spitz-Ahorn",
    distribution: "ToBeDone",
    totalPlanted: 90,
    maxSizeMeters: "20-25",
    lifeExpectancyYears: "Around 250 years.",
    frequency: "Common.",
    habitat: "Various, often in urban areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Norway maple is valued for its shade and attractive foliage.",
  ),
  "Acer pseudoplatanus": PlantData(
    scientificName: "Acer pseudoplatanus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Bergahorn",
    distribution: "ToBeDone",
    totalPlanted: 303,
    maxSizeMeters: "40",
    lifeExpectancyYears: "Up to 400 years.",
    frequency: "Common.",
    habitat: "Woodlands and mixed forests.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Sycamore maple is known for its large, palmately lobed leaves.",
  ),
  "Alnus glutinosa": PlantData(
    scientificName: "Alnus glutinosa",
    pathPicture: "./images/plants/Alnus glutinosa.jpeg",
    plantType: "Hauptbaumart",
    commonName: "Schwarzerle",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "20-25",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Wetlands and riverbanks.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common alder is associated with wet or waterlogged soils.",
  ),
  "Amelanchier ovalis": PlantData(
    scientificName: "Amelanchier ovalis",
    pathPicture: "./images/plants/Amelanchier ovalis.jpeg",
    plantType: "Strauch",
    commonName: "Gewöhnliche Felsenbirne",
    distribution: "ToBeDone",
    totalPlanted: 63,
    maxSizeMeters: "3-8",
    lifeExpectancyYears: "Up to 50 years.",
    frequency: "Common.",
    habitat: "Woodlands and heathlands.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Serviceberries produce edible berries.",
  ),
  "Anemone nemorosa": PlantData(
    scientificName: "Anemone nemorosa",
    pathPicture: "./images/plants/Anemone nemorosa.jpeg",
    plantType: "Bodendecker",
    commonName: "Buschwindröschen",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.1-0.3",
    lifeExpectancyYears: "About 50 years.",
    frequency: "Common.",
    habitat: "Woodlands and meadows.",
    leafType: "Deciduous.",
    floweringSeason: "March to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Also known as wood anemone, it spreads by rhizomes.",
  ),
  "Athyrium filix-femina": PlantData(
    scientificName: "Athyrium filix-femina",
    pathPicture: "./images/plants/Athyrium filix-femina.jpeg",
    plantType: "Bodendecker",
    commonName: "Wald-Frauenfarn",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "1",
    lifeExpectancyYears: "Up to 100 years.",
    frequency: "Common.",
    habitat: "Woodlands and shady areas.",
    leafType: "Deciduous.",
    floweringSeason: "Not applicable (fern).",
    conservationStatus: "Least Concern.",
    interestingFact: "Lady fern is a common woodland fern species.",
  ),
  "Berberis vulgaris": PlantData(
    scientificName: "Berberis vulgaris",
    pathPicture: "./images/plants/Berberis vulgaris.jpeg",
    plantType: "Strauch",
    commonName: "Gewöhnliche Berberitze",
    distribution: "ToBeDone",
    totalPlanted: 83,
    maxSizeMeters: "2-3",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands and hedgerows.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common barberry is known for its spiny branches.",
  ),
  "Betula pendula": PlantData(
    scientificName: "Betula pendula",
    pathPicture: "./images/plants/Betula pendula.jpeg",
    plantType: "Nebenbaumart",
    commonName: "Hängebirke",
    distribution: "ToBeDone",
    totalPlanted: 81,
    maxSizeMeters: "15-25",
    lifeExpectancyYears: "Up to 100 years.",
    frequency: "Common.",
    habitat: "Woodlands and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Silver birch is valued for its slender, drooping branches.",
  ),
  "Betula pubescens": PlantData(
    scientificName: "Betula pubescens",
    pathPicture: "./images/plants/Betula pendula.jpeg",
    plantType: "Nebenbaumart",
    commonName: "Moor-Birke",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "15-25",
    lifeExpectancyYears: "Up to 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, heathlands, and moors.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Downy birch is more tolerant of wetter conditions than silver birch.",
  ),
  "Brachypodium sylvaticum": PlantData(
    scientificName: "Brachypodium sylvaticum",
    pathPicture: "./images/plants/Brachypodium sylvaticum.jpeg",
    plantType: "Bodendecker",
    commonName: "Wald-Zwenke",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "1",
    lifeExpectancyYears: "Around 1-3 years.",
    frequency: "Common.",
    habitat: "Woodlands and grasslands.",
    leafType: "Grass, not applicable.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "False brome is a common grass species in woodland areas.",
  ),
  "Carex brizoides": PlantData(
    scientificName: "Carex brizoides",
    pathPicture: "./images/plants/Carex brizoides.jpeg",
    plantType: "Bodendecker",
    commonName: "Zittergras-Segge",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.3-0.6",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and wetlands.",
    leafType: "Grass, not applicable.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common quaking grass is known for its distinctive nodding flowerheads.",
  ),
  "Carpinus betulus": PlantData(
    scientificName: "Carpinus betulus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Hainbuche",
    distribution: "ToBeDone",
    totalPlanted: 354,
    maxSizeMeters: "15-25",
    lifeExpectancyYears: "Up to 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Hornbeam is often used for hedging and screening.",
  ),
  "Cornus sanguinea": PlantData(
    scientificName: "Cornus sanguinea",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Blutroter Hartriegel",
    distribution: "ToBeDone",
    totalPlanted: 133,
    maxSizeMeters: "1.5-3",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Woodlands, scrub, and hedgerows.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common dogwood has distinctive red stems in winter.",
  ),
  "Corylus avellana": PlantData(
    scientificName: "Corylus avellana",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Hasel",
    distribution: "ToBeDone",
    totalPlanted: 218,
    maxSizeMeters: "3-8",
    lifeExpectancyYears: "Up to 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "January to April.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common hazel produces edible nuts.",
  ),
  "Crataegus laevigata agg": PlantData(
    scientificName: "Crataegus laevigata agg",
    pathPicture: "./images/plants/Crataegus laevigata.jpeg",
    plantType: "Strauch",
    commonName: "Zweigriffeliger Weißdorn",
    distribution: "ToBeDone",
    totalPlanted: 35,
    maxSizeMeters: "5-8",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Midland hawthorn is part of a complex group of hawthorn species.",
  ),
  "Crataegus monogyna": PlantData(
    scientificName: "Crataegus monogyna",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Weißdorn",
    distribution: "ToBeDone",
    totalPlanted: 60,
    maxSizeMeters: "5-10",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common hawthorn has thorny branches and clusters of white flowers.",
  ),
  "Cytisus Scoparius": PlantData(
    scientificName: "Cytisus Scoparius",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Besen Ginster",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "1-3",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Heaths, open woodlands, and disturbed areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common broom is known for its bright yellow flowers.",
  ),
  "Euonymus europaeus": PlantData(
    scientificName: "Euonymus europaeus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "europ. Pfaffenhütchen",
    distribution: "ToBeDone",
    totalPlanted: 93,
    maxSizeMeters: "2-6",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "European spindle produces striking pink fruit capsules.",
  ),
  "Fagus sylvatica": PlantData(
    scientificName: "Fagus sylvatica",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Buche",
    distribution: "ToBeDone",
    totalPlanted: 354,
    maxSizeMeters: "25-35",
    lifeExpectancyYears: "Up to 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, often forming pure stands.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "European beech is known for its smooth, silver-gray bark.",
  ),
  "Frangula alnus": PlantData(
    scientificName: "Frangula alnus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Faulbaum",
    distribution: "ToBeDone",
    totalPlanted: 163,
    maxSizeMeters: "2-6",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Wetlands, riverbanks, and woodlands.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Alder buckthorn is the larval food plant for brimstone butterflies.",
  ),
  "Fraxinus Excelsior": PlantData(
    scientificName: "Fraxinus Excelsior",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Esche",
    distribution: "ToBeDone",
    totalPlanted: 143,
    maxSizeMeters: "25-35",
    lifeExpectancyYears: "Up to 200 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common ash is threatened by ash dieback disease.",
  ),
  "Fraxinus excelsior": PlantData(
    scientificName: "Fraxinus excelsior",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Esche",
    distribution: "ToBeDone",
    totalPlanted: 180,
    maxSizeMeters: "25-35",
    lifeExpectancyYears: "Up to 200 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and parks.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common ash is threatened by ash dieback disease.",
  ),
  "Galium odoratum": PlantData(
    scientificName: "Galium odoratum",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Waldmeister",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.1-0.5",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands and shady areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Sweet woodruff is valued for its sweet-scented flowers and leaves.",
  ),
  "Galium sylvaticum": PlantData(
    scientificName: "Galium sylvaticum",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Wald-Labkraut",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.3-0.6",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Wood bedstraw is often found in shady places.",
  ),
  "Ilex aquifolium": PlantData(
    scientificName: "Ilex aquifolium",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Stechpalme",
    distribution: "ToBeDone",
    totalPlanted: 105,
    maxSizeMeters: "10-25",
    lifeExpectancyYears: "Up to 300 years.",
    frequency: "Common.",
    habitat: "Woodlands and hedgerows.",
    leafType: "Evergreen.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common holly is associated with winter festivities.",
  ),
  "Impatiens noli-tangere": PlantData(
    scientificName: "Impatiens noli-tangere",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Großes Springkraut",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.1-0.4",
    lifeExpectancyYears: "Around 1-2 years.",
    frequency: "Common.",
    habitat: "Woodlands and damp areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to October.",
    conservationStatus: "Least Concern.",
    interestingFact: "Touch-me-not has explosive seed capsules.",
  ),
  "Lamium galeobdolon": PlantData(
    scientificName: "Lamium galeobdolon",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Goldnessel",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "0.1-0.5",
    lifeExpectancyYears: "Around 5 years.",
    frequency: "Common.",
    habitat: "Woodlands and shady places.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Yellow archangel is known for its yellow flowers and square stems.",
  ),
  "Larix decidua": PlantData(
    scientificName: "Larix decidua",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Polnische Lärche",
    distribution: "ToBeDone",
    totalPlanted: 71,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Up to 500 years.",
    frequency: "Common.",
    habitat: "Alpine and subalpine zones.",
    leafType: "Deciduous (needle-like leaves).",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Polish larch is a deciduous conifer.",
  ),
  "Lonicera periclymenum": PlantData(
    scientificName: "Lonicera periclymenum",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Wald-Geißblatt",
    distribution: "ToBeDone",
    totalPlanted: 35,
    maxSizeMeters: "3-6",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common honeysuckle has fragrant, tubular flowers.",
  ),
  "Malus sylvestris": PlantData(
    scientificName: "Malus sylvestris",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Wild Apfel",
    distribution: "ToBeDone",
    totalPlanted: 91,
    maxSizeMeters: "5-10",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wild apple is the ancestor of many cultivated apple varieties.",
  ),
  "Oxalis acetosella": PlantData(
    scientificName: "Oxalis acetosella",
    pathPicture: "./images/plants/Oxalis acetosella.jpeg",
    plantType: "Bodendecker",
    commonName: "Sauerklee",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.1-0.2",
    lifeExpectancyYears: "Around 5 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and damp areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wood sorrel's leaves fold up at night and in low light conditions.",
  ),
  "Pinus sylvestris": PlantData(
    scientificName: "Pinus sylvestris",
    pathPicture: "./images/plants/Pinus sylvestris.jpeg",
    plantType: "Nebenbaumart",
    commonName: "Waldkiefer",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "20-35",
    lifeExpectancyYears: "Up to 500 years.",
    frequency: "Common.",
    habitat: "Woodlands, heathlands, and sandy areas.",
    leafType: "Evergreen (needle-like leaves).",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Scots pine is the national tree of Scotland.",
  ),
  "Poa nemoralis": PlantData(
    scientificName: "Poa nemoralis",
    pathPicture: "./images/plants/Poa nemoralis.jpeg",
    plantType: "Bodendecker",
    commonName: "Hain-Rispengras",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.2-0.6",
    lifeExpectancyYears: "Around 1-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Grass, not applicable.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wood meadow grass is a common grass in woodland habitats.",
  ),
  "Populus tremula": PlantData(
    scientificName: "Populus tremula",
    pathPicture: "./images/plants/Populus tremula.jpeg",
    plantType: "Nebenbaumart",
    commonName: "Zitterpappel",
    distribution: "ToBeDone",
    totalPlanted: 115,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, open areas, and riverbanks.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common aspen has leaves that flutter in the wind due to flattened petioles.",
  ),
  "Potentilla sterilis": PlantData(
    scientificName: "Potentilla sterilis",
    pathPicture: "./images/plants/Potentilla sterilis.jpeg",
    plantType: "Bodendecker",
    commonName: "Erdbeer-Fingerkraut",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.1-0.3",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to August.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Barren strawberry produces small, strawberry-like fruits.",
  ),
  "Prunus Padus": PlantData(
    scientificName: "Prunus Padus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Traubenkirsche",
    distribution: "ToBeDone",
    totalPlanted: 121,
    maxSizeMeters: "8-15",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Bird cherry is known for its fragrant, drooping flower clusters.",
  ),
  "Prunus Spinosa": PlantData(
    scientificName: "Prunus Spinosa",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Schlehe",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "2-4",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Blackthorn is the host plant for the caterpillars of several butterfly species.",
  ),
  "Prunus avium": PlantData(
    scientificName: "Prunus avium",
    pathPicture: "./images/plants/Prunus avium.jpeg",
    plantType: "Hauptbaumart",
    commonName: "Vogel-Kische",
    distribution: "ToBeDone",
    totalPlanted: 142,
    maxSizeMeters: "15-25",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "March to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wild cherry is the ancestor of many cultivated cherry varieties.",
  ),
  "Prunus cerasifera": PlantData(
    scientificName: "Prunus cerasifera",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Kirschpflaume",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "2-6",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Cherry plum is often cultivated for its ornamental value and edible fruits.",
  ),
  "Prunus spinosa": PlantData(
    scientificName: "Prunus spinosa",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Schlehe",
    distribution: "ToBeDone",
    totalPlanted: 65,
    maxSizeMeters: "2-4",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and scrub.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Blackthorn is the host plant for the caterpillars of several butterfly species.",
  ),
  "Pyrus pyraster": PlantData(
    scientificName: "Pyrus pyraster",
    pathPicture: "./images/plants/Pyrus pyraster.jpeg",
    plantType: "Strauch",
    commonName: "Wild-Birne",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "10-20",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Wild pear is native to Europe and Western Asia.",
  ),
  "Pyrus pyraster agg": PlantData(
    scientificName: "Pyrus pyraster agg",
    pathPicture: "./images/plants/Pyrus pyraster.jpeg",
    plantType: "Nebenbaumart",
    commonName: "Wild Birne",
    distribution: "ToBeDone",
    totalPlanted: 91,
    maxSizeMeters: "10-20",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "The Pyrus pyraster aggregate includes several wild pear species.",
  ),
  "Quercus patrea": PlantData(
    scientificName: "Quercus patrea",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Traubeneiche",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "15-25",
    lifeExpectancyYears: "Around 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, mixed forests, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Sessile oak is one of the native oaks in the British Isles.",
  ),
  "Quercus petraea": PlantData(
    scientificName: "Quercus petraea",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Traubeneiche",
    distribution: "ToBeDone",
    totalPlanted: 194,
    maxSizeMeters: "20-40",
    lifeExpectancyYears: "Around 500 years.",
    frequency: "Common.",
    habitat: "Woodlands, mixed forests, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Commonly known as sessile oak, it lacks the acorn stalk found in pedunculate oak.",
  ),
  "Quercus robur": PlantData(
    scientificName: "Quercus robur",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Stieleiche",
    distribution: "ToBeDone",
    totalPlanted: 274,
    maxSizeMeters: "20-40",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, mixed forests, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Pedunculate oak is a long-lived species with significant cultural and ecological importance.",
  ),
  "Rhammus cathartica": PlantData(
    scientificName: "Rhammus cathartica",
    pathPicture: "./images/plants/Rhammus cathartica.jpeg",
    plantType: "Strauch",
    commonName: "Kreuzdorn",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "2-6",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common buckthorn is the larval host for the brimstone butterfly.",
  ),
  "Rhamnus frangula": PlantData(
    scientificName: "Rhamnus frangula",
    pathPicture: "./images/plants/Rhamnus frangula.jpeg",
    plantType: "Strauch",
    commonName: "Faulbaum",
    distribution: "ToBeDone",
    totalPlanted: 63,
    maxSizeMeters: "2-6",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Alder buckthorn is the larval food plant for brimstone butterflies.",
  ),
  "Ribes rubrum": PlantData(
    scientificName: "Ribes rubrum",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Rote Johannisbeere",
    distribution: "ToBeDone",
    totalPlanted: 75,
    maxSizeMeters: "1-2",
    lifeExpectancyYears: "Around 15 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Red currant is cultivated for its edible berries.",
  ),
  "Ribes rubrum s. str.": PlantData(
    scientificName: "Ribes rubrum s. str.",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Rote Johannisbeere",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "1-2",
    lifeExpectancyYears: "Around 15 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "This refers to the strict sense (s. str.) of red currant.",
  ),
  "Rosa arvensis": PlantData(
    scientificName: "Rosa arvensis",
    pathPicture: "./images/plants/Rosa arvensis.jpeg",
    plantType: "Strauch",
    commonName: "Feld-Rose",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "1-3",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Field rose is known for its fragrant flowers.",
  ),
  "Rosa canina agg": PlantData(
    scientificName: "Rosa canina agg",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Hunds-Rose",
    distribution: "ToBeDone",
    totalPlanted: 83,
    maxSizeMeters: "1-3",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to August.",
    conservationStatus: "Least Concern.",
    interestingFact: "Dog rose is the most common wild rose species.",
  ),
  "Rubus caesius": PlantData(
    scientificName: "Rubus caesius",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Kratzbeere",
    distribution: "ToBeDone",
    totalPlanted: 30,
    maxSizeMeters: "0.5-1.5",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact: "Dewberry is a low-growing relative of the blackberry.",
  ),
  "Rubus idaeus": PlantData(
    scientificName: "Rubus idaeus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Himbeere",
    distribution: "ToBeDone",
    totalPlanted: 243,
    maxSizeMeters: "1-2",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact: "Raspberry is well-known for its delicious red berries.",
  ),
  "Rubus sect. Rubus": PlantData(
    scientificName: "Rubus sect. Rubus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Brombeere",
    distribution: "ToBeDone",
    totalPlanted: 65,
    maxSizeMeters: "1-3",
    lifeExpectancyYears: "Around 20 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "This refers to the section (sect.) of the Rubus genus, which includes many bramble species.",
  ),
  "Salix alba": PlantData(
    scientificName: "Salix alba",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Silberweide",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "10-25",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Riverbanks, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "White willow is the source of salicylic acid, a precursor to aspirin.",
  ),
  "Salix aurita": PlantData(
    scientificName: "Salix aurita",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Ohr-Weide",
    distribution: "ToBeDone",
    totalPlanted: 20,
    maxSizeMeters: "1-4",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Riverbanks, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Eared willow is named for its distinctive ear-shaped stipules.",
  ),
  "Salix caprea": PlantData(
    scientificName: "Salix caprea",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Salweide",
    distribution: "ToBeDone",
    totalPlanted: 65,
    maxSizeMeters: "4-10",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Goat willow is an important early source of nectar for bees.",
  ),
  "Salix purpurea": PlantData(
    scientificName: "Salix purpurea",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Purpur-Weide",
    distribution: "ToBeDone",
    totalPlanted: 103,
    maxSizeMeters: "2-6",
    lifeExpectancyYears: "Around 30 years.",
    frequency: "Common.",
    habitat: "Riverbanks, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to May.",
    conservationStatus: "Least Concern.",
    interestingFact: "Purple willow is known for its purple stems in winter.",
  ),
  "Sambucus Nigra": PlantData(
    scientificName: "Sambucus Nigra",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Schwarzer Holunder",
    distribution: "ToBeDone",
    totalPlanted: 91,
    maxSizeMeters: "3-6",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Common elder has clusters of small, creamy-white flowers and dark berries.",
  ),
  "Sambucus nigra": PlantData(
    scientificName: "Sambucus nigra",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Schwarzer Holunder",
    distribution: "ToBeDone",
    totalPlanted: 110,
    maxSizeMeters: "3-6",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Black elder is known for its use in traditional medicine and as a flavoring in beverages.",
  ),
  "Sambucus racemosa": PlantData(
    scientificName: "Sambucus racemosa",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Roter Holunder",
    distribution: "ToBeDone",
    totalPlanted: 30,
    maxSizeMeters: "2-4",
    lifeExpectancyYears: "Around 50 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact: "Red elderberry produces clusters of small red berries.",
  ),
  "Sorbus aucuparia": PlantData(
    scientificName: "Sorbus aucuparia",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Eberesche",
    distribution: "ToBeDone",
    totalPlanted: 166,
    maxSizeMeters: "5-12",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Rowan is often associated with folklore and has symbolic importance.",
  ),
  "Sorbus torminalis": PlantData(
    scientificName: "Sorbus torminalis",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Elsbeere",
    distribution: "ToBeDone",
    totalPlanted: 176,
    maxSizeMeters: "10-20",
    lifeExpectancyYears: "Around 100 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wild service tree has distinctive lobed leaves and small fruits.",
  ),
  "Stellaria holostea": PlantData(
    scientificName: "Stellaria holostea",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Große Steinmiere",
    distribution: "ToBeDone",
    totalPlanted: 50,
    maxSizeMeters: "0.3-0.6",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Adder's tongue spearwort has star-shaped white flowers.",
  ),
  "Taxus baccata": PlantData(
    scientificName: "Taxus baccata",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Europäische Eibe",
    distribution: "ToBeDone",
    totalPlanted: 70,
    maxSizeMeters: "15-20",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, hedgerows, and open areas.",
    leafType: "Evergreen (needle-like leaves).",
    floweringSeason: "March to April.",
    conservationStatus: "Least Concern.",
    interestingFact: "Common yew is often associated with ancient churchyards.",
  ),
  "Tilia Cordata": PlantData(
    scientificName: "Tilia Cordata",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Winterlinde",
    distribution: "ToBeDone",
    totalPlanted: 163,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Small-leaved lime is valued for its fragrant flowers and heart-shaped leaves.",
  ),
  "Tilia cordata": PlantData(
    scientificName: "Tilia cordata",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Winterlinde",
    distribution: "ToBeDone",
    totalPlanted: 85,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Small-leaved lime is valued for its fragrant flowers and heart-shaped leaves.",
  ),
  "Tilia platyphyllos": PlantData(
    scientificName: "Tilia platyphyllos",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Sommerlinde",
    distribution: "ToBeDone",
    totalPlanted: 95,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Large-leaved lime has larger leaves compared to small-leaved lime.",
  ),
  "Tilia tomentosa": PlantData(
    scientificName: "Tilia tomentosa",
    pathPicture: "./images/plants/Default.png",
    plantType: "Hauptbaumart",
    commonName: "Silberlinde",
    distribution: "ToBeDone",
    totalPlanted: 40,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Around 1,000 years.",
    frequency: "Common.",
    habitat: "Woodlands, parks, and avenues.",
    leafType: "Deciduous.",
    floweringSeason: "June to July.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Silver lime has silvery-white hairs on the underside of its leaves.",
  ),
  "Ulmus glabra": PlantData(
    scientificName: "Ulmus glabra",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Berg-Ulme",
    distribution: "ToBeDone",
    totalPlanted: 71,
    maxSizeMeters: "25-35",
    lifeExpectancyYears: "Around 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Wych elm is the only elm species native to the British Isles.",
  ),
  "Ulmus laevis": PlantData(
    scientificName: "Ulmus laevis",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Flatterulme",
    distribution: "ToBeDone",
    totalPlanted: 186,
    maxSizeMeters: "25-35",
    lifeExpectancyYears: "Around 300 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact: "European white elm is known for its smooth, grey bark.",
  ),
  "Ulmus minor": PlantData(
    scientificName: "Ulmus minor",
    pathPicture: "./images/plants/Default.png",
    plantType: "Nebenbaumart",
    commonName: "Feldulme",
    distribution: "ToBeDone",
    totalPlanted: 111,
    maxSizeMeters: "20-30",
    lifeExpectancyYears: "Around 200 years.",
    frequency: "Common.",
    habitat: "Woodlands, riverbanks, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "February to March.",
    conservationStatus: "Least Concern.",
    interestingFact: "Field elm is susceptible to Dutch elm disease.",
  ),
  "Vaccinium corymbosum": PlantData(
    scientificName: "Vaccinium corymbosum",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Heidelbeere",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "1-3",
    lifeExpectancyYears: "Around 60 years.",
    frequency: "Common.",
    habitat: "Woodlands, heathlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact: "Highbush blueberry is cultivated for its edible berries.",
  ),
  "Viburnum opulus": PlantData(
    scientificName: "Viburnum opulus",
    pathPicture: "./images/plants/Default.png",
    plantType: "Strauch",
    commonName: "Schneeball",
    distribution: "ToBeDone",
    totalPlanted: 123,
    maxSizeMeters: "2-5",
    lifeExpectancyYears: "Around 80 years.",
    frequency: "Common.",
    habitat: "Woodlands, wetlands, and open areas.",
    leafType: "Deciduous.",
    floweringSeason: "May to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Guelder rose has clusters of white flowers and bright red berries.",
  ),
  "Viola reichenbachiana": PlantData(
    scientificName: "Viola reichenbachiana",
    pathPicture: "./images/plants/Default.png",
    plantType: "Bodendecker",
    commonName: "Wald-Veilchen",
    distribution: "ToBeDone",
    totalPlanted: 25,
    maxSizeMeters: "0.1-0.2",
    lifeExpectancyYears: "Around 2-3 years.",
    frequency: "Common.",
    habitat: "Woodlands, meadows, and grassy areas.",
    leafType: "Deciduous.",
    floweringSeason: "April to June.",
    conservationStatus: "Least Concern.",
    interestingFact:
        "Early dog-violet is one of the first violets to bloom in spring.",
  ),
};
