class PlantData {
  final String scientificName;
  final String commonName;
  final String? pathPicture;
  final String distribution;
  final int maxSizeMeters;
  final int totalPlanted;
  final double lifeExpectancyYears;
  final String frequency;
  final String habitat;
  final String leafType;
  final String floweringSeason;
  final String conservationStatus;
  final String interestingFact;

  PlantData({
    required this.scientificName,
    required this.commonName,
    required this.distribution,
    required this.maxSizeMeters,
    required this.totalPlanted,
    required this.lifeExpectancyYears,
    required this.frequency,
    required this.habitat,
    required this.leafType,
    required this.floweringSeason,
    required this.conservationStatus,
    required this.interestingFact,
    required this.pathPicture,
  });
}

Map<String, PlantData> allTrees = {
  "Quercus spp.": PlantData(
    scientificName: "Quercus spp.",
    pathPicture: "./images/trees/Eiche.png",
    commonName: "Oak",
    distribution: "Europe",
    totalPlanted: 0,
    maxSizeMeters: 40,
    lifeExpectancyYears: 100 - 1000,
    frequency: "Common",
    habitat: "Various, including forests and woodlands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "Oak trees support a rich ecosystem, providing food and shelter for numerous species.",
  ),
  "Pinus sylvestris": PlantData(
    scientificName: "Pinus sylvestris",
    pathPicture: "./images/trees/Fichte.png",
    commonName: "Scots Pine",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 35,
    lifeExpectancyYears: 150 - 300,
    frequency: "Common",
    habitat: "Coniferous forests",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "Scots Pine is the national tree of Scotland and has distinctive orange-brown bark.",
  ),
  "Fagus sylvatica": PlantData(
    scientificName: "Fagus sylvatica",
    pathPicture: "./images/trees/Default.png",
    commonName: "European Beech",
    distribution: "Europe",
    totalPlanted: 0,
    maxSizeMeters: 40,
    lifeExpectancyYears: 150 - 200,
    frequency: "Common",
    habitat: "Deciduous forests",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "European Beech has smooth gray bark and is valued for its timber.",
  ),
  "Betula pendula": PlantData(
    scientificName: "Betula pendula",
    pathPicture: "./images/trees/Birken.png",
    commonName: "Silver Birch",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 25,
    lifeExpectancyYears: 80 - 100,
    frequency: "Common",
    habitat: "Woodlands, heathlands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "Silver Birch is known for its distinctive white bark and slender branches.",
  ),
  "Fraxinus excelsior": PlantData(
    scientificName: "Fraxinus excelsior",
    pathPicture: "./images/trees/Default.png",
    commonName: "Common Ash",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 35,
    lifeExpectancyYears: 200 - 300,
    frequency: "Common",
    habitat: "Woodlands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "Common Ash is a hardwood tree used in furniture and tool making.",
  ),
  "Carpinus betulus": PlantData(
    scientificName: "Carpinus betulus",
    pathPicture: "./images/trees/Default.png",
    commonName: "European Hornbeam",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 20,
    lifeExpectancyYears: 120 - 150,
    frequency: "Common",
    habitat: "Woodlands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "European Hornbeam has distinctive serrated leaves and hard wood.",
  ),
  "Picea abies": PlantData(
    scientificName: "Picea abies",
    pathPicture: "./images/trees/Default.png",
    commonName: "Norway Spruce",
    distribution: "Europe",
    totalPlanted: 0,
    maxSizeMeters: 60,
    lifeExpectancyYears: 200 - 300,
    frequency: "Common",
    habitat: "Coniferous forests",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact: "Norway Spruce is a popular Christmas tree species.",
  ),
  "Ilex aquifolium": PlantData(
    scientificName: "Ilex aquifolium",
    pathPicture: "./images/trees/Default.png",
    commonName: "European Holly",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 15,
    lifeExpectancyYears: 300 - 500,
    frequency: "Common",
    habitat: "Woodlands",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "European Holly is known for its glossy, spiky leaves and red berries.",
  ),
  "Juglans regia": PlantData(
    scientificName: "Juglans regia",
    pathPicture: "./images/trees/Default.png",
    commonName: "Common Walnut",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 25,
    lifeExpectancyYears: 150 - 200,
    frequency: "Common",
    habitat: "Woodlands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact: "Common Walnut produces valuable timber and edible nuts.",
  ),
  "Taxus baccata": PlantData(
    scientificName: "Taxus baccata",
    pathPicture: "./images/trees/Default.png",
    commonName: "European Yew",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 20,
    lifeExpectancyYears: 500 - 2000,
    frequency: "Common",
    habitat: "Woodlands",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "European Yew is a long-lived tree with poisonous red berries.",
  ),
  "Pinus peuce": PlantData(
    scientificName: "Pinus peuce",
    pathPicture: "./images/trees/Default.png",
    commonName: "Macedonian Pine",
    distribution: "Balkans",
    totalPlanted: 0,
    maxSizeMeters: 25,
    lifeExpectancyYears: 200 - 500,
    frequency: "Rare",
    habitat: "Mountainous regions",
    leafType: "Evergreen",
    floweringSeason: "Summer",
    conservationStatus: "Vulnerable",
    interestingFact:
        "Macedonian Pine has distinctive long needles and is adapted to harsh mountainous environments.",
  ),
  "Sorbus arranensis": PlantData(
    scientificName: "Sorbus arranensis",
    pathPicture: "./images/trees/Default.png",
    commonName: "Arran Whitebeam",
    distribution: "Isle of Arran, Scotland",
    totalPlanted: 0,
    maxSizeMeters: 8,
    lifeExpectancyYears: 50 - 100,
    frequency: "Rare",
    habitat: "Woodlands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Endangered",
    interestingFact:
        "Arran Whitebeam is a rare tree found only on the Isle of Arran in Scotland.",
  ),
  "Picea omorika": PlantData(
    scientificName: "Picea omorika",
    pathPicture: "./images/trees/Default.png",
    commonName: "Serbian Spruce",
    distribution: "Balkans",
    totalPlanted: 0,
    maxSizeMeters: 40,
    lifeExpectancyYears: 150 - 300,
    frequency: "Rare",
    habitat: "Coniferous forests",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Vulnerable",
    interestingFact:
        "Serbian Spruce has a narrow, spire-like crown and is native to the Balkan Peninsula.",
  ),
  "Quercus faginea": PlantData(
    scientificName: "Quercus faginea",
    pathPicture: "./images/trees/Default.png",
    commonName: "Lusitanian Oak",
    distribution: "Iberian Peninsula",
    totalPlanted: 0,
    maxSizeMeters: 20,
    lifeExpectancyYears: 150 - 200,
    frequency: "Rare",
    habitat: "Woodlands",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Near Threatened",
    interestingFact:
        "Lusitanian Oak is an evergreen oak species native to Portugal and Spain.",
  ),
  "Cedrus atlantica": PlantData(
    scientificName: "Cedrus atlantica",
    pathPicture: "./images/trees/Default.png",
    commonName: "Atlas Cedar",
    distribution: "Atlas Mountains, Morocco",
    totalPlanted: 0,
    maxSizeMeters: 40,
    lifeExpectancyYears: 120 - 200,
    frequency: "Rare",
    habitat: "Mountainous regions",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "Atlas Cedar is a large evergreen conifer with distinctive blue-green needles.",
  ),
  "Pinus nigra subsp. salzmannii": PlantData(
    scientificName: "Pinus nigra subsp. salzmannii",
    pathPicture: "./images/trees/Default.png",
    commonName: "Balearic Pine",
    distribution: "Balearic Islands",
    totalPlanted: 0,
    maxSizeMeters: 30,
    lifeExpectancyYears: 100 - 200,
    frequency: "Rare",
    habitat: "Mountainous regions",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Endangered",
    interestingFact:
        "Balearic Pine is native to the Balearic Islands and is threatened by habitat loss.",
  ),
  "Pyrus bourgaeana": PlantData(
    scientificName: "Pyrus bourgaeana",
    pathPicture: "./images/trees/Default.png",
    commonName: "Iberian Pear",
    distribution: "Iberian Peninsula",
    totalPlanted: 0,
    maxSizeMeters: 15,
    lifeExpectancyYears: 50 - 100,
    frequency: "Rare",
    habitat: "Woodlands, scrublands",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Vulnerable",
    interestingFact:
        "Iberian Pear produces small, hard pears and is found in southwestern Europe.",
  ),
  "Pinus heldreichii": PlantData(
    scientificName: "Pinus heldreichii",
    pathPicture: "./images/trees/Default.png",
    commonName: "Bosnian Pine",
    distribution: "Balkans",
    totalPlanted: 0,
    maxSizeMeters: 25,
    lifeExpectancyYears: 150 - 300,
    frequency: "Rare",
    habitat: "Mountainous regions",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Near Threatened",
    interestingFact:
        "Bosnian Pine is a slow-growing pine species native to the Balkan Peninsula.",
  ),
  "Juniperus sabina": PlantData(
    scientificName: "Juniperus sabina",
    pathPicture: "./images/trees/Default.png",
    commonName: "Savin Juniper",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 2,
    lifeExpectancyYears: 50 - 100,
    frequency: "Rare",
    habitat: "Rocky areas, hillsides",
    leafType: "Evergreen",
    floweringSeason: "Spring",
    conservationStatus: "Least Concern",
    interestingFact:
        "Savin Juniper is a low-growing juniper species with scale-like leaves.",
  ),
  "Populus nigra": PlantData(
    scientificName: "Populus nigra",
    pathPicture: "./images/trees/Default.png",
    commonName: "Black Poplar",
    distribution: "Europe, Asia",
    totalPlanted: 0,
    maxSizeMeters: 30,
    lifeExpectancyYears: 100 - 200,
    frequency: "Rare",
    habitat: "Riparian zones",
    leafType: "Deciduous",
    floweringSeason: "Spring",
    conservationStatus: "Endangered",
    interestingFact:
        "Black Poplar is a large deciduous tree with dark gray bark and diamond-shaped leaves.",
  ),
};
